### ISSUE TITLE
Cannot read property "length" of undefined

### ISSUE THREAD

**Issue by mikelsx** [steam-forward/node-steam-forum#10]
`if(body.response.trade_offers_received){`
     `  body.response.trade_offers_received.forEach(function(offer) {`
       `   if (offer.trade_offer_state == 2) {`
			`var items = offer.items_to_receive;`
			`var exception = false;`
			`for(var i=0; i< items.length;i++)`
          `  {`
			`if(items[i].appid != "730")`
               ` {`
                   ` exception = true;`
                    
              `  }`
			`}`
         `   console.log(offer);
           ` console.log();`
			`if (items != "") {
				if(!offer.items_to_give && !exception){
                     offers.acceptOffer({tradeOfferId: offer.tradeofferid});
					logger.info("A Trade has been accepted: " + offer.steamid_other);
					    for (i = 0; i < items.length; i++){
                        logger.info("Items received (assetid & classid): " + items[i]["assetid"] + items[i]["classid"]);
                    }
                }else {
                    offers.declineOffer({tradeOfferId: offer.tradeofferid});
					logger.info("A Trade has been declined: " + offer.steamid_other);
                }
			}  else {
				offers.declineOffer({tradeOfferId: offer.tradeofferid});
					logger.info("Trade has been declined | Steam ID: " + offer.steamid_other);
			}
          }
        });`

Error:
`  for(var i=0; i< items.length;i++)
Cannot read property 'length' of undefined`

that means the `items` variable is empty, why?

**Comment by dragonbanshee** [comment]
It can be empty for many reasons. A common one is that it hasn't loaded the other items yet. Try putting the for loop in a timeout and see what happens.

**Comment by mikelsx** [comment]
solved, i had to create a Steam API key on my bot account.
