### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by dogmagames** [steam-forward/node-steam-forum#101]
After about 1 hour after the bot logged in, im getting error 401 when trying to create a trade offer

**Comment by andrewda** [comment]
It's probably best to call `webLogOn` when you receive an error 401. The issue might be that your cookies are getting expired.

**Comment by dogmagames** [comment]
@andrewda Yes, youre right.I understand that my cookies are expiring, but i dont know why my...
You have any clues?

**Comment by scholtzm** [comment]
Some possibilities ...

1. You got disconnected from Steam and you didn't refresh the cookies.
2. You logged into bot's Steam accont via steamcommunity.com on another device.
