### ISSUE TITLE
Check if item is in existing steam offer - multiple trade offers with the same items.

### ISSUE THREAD

**Issue by spyrek10** [steam-forward/node-steam-forum#103]
Hello, 
I have a little problem with my bot.
As you know, you can send multiple trade offers with the same items. For example: 
Offer 1: dragon lore (id: xxx), awp asiimov(id: yyy) 
Offer 2: AK Vulcan(id: zzz), dragon lore(id: xxx)

When you accept offer 1, the offer 2 will be automatically declined, bot has a forEach which handles the offers, so probably offers are processed at the same time which leads to accepting both offers(in code). Checking offer state right before accepting isn't working.

Can I solve it in other way than storing item IDs from accepted offers and check if incomming offer has already accepted items?

Will sequential offer processing be much slower than using forEach?

**Comment by scholtzm** [comment]
Are you checking the response from the accept call?

**Comment by spyrek10** [comment]
I'm using acceptOffer callback:
offers.acceptOffer({tradeOfferId: offer.tradeofferid}, function(err){
code goes here
 });

Does the acceptOffer method has additional attributes, like response?

**Comment by scholtzm** [comment]
Callback should have 2 arguments: error and response.

Are you saying that both offers pass without returning error?

**Comment by spyrek10** [comment]
In fact I didn't check the error, after adding the check I'm getting error 504, so I suppose that it's working fine. 
Thanks for help.

**Comment by scholtzm** [comment]
I wouldn't rely specifically on 504. Steam often returns this when the servers are slow.

But in general, if `error` is truthy, you should definitely not consider the trade accepted.
