### ISSUE TITLE
Persisting message:  An uncaughtException was found, the program will end.TypeError: Cannot read property 'send' of undefined 

### ISSUE THREAD

**Issue by blanko18** [steam-forward/node-steam-forum#108]
Hi,

We are currently getting this error message on our bot.

" An uncaughtException was found, the program will end.TypeError: Cannot read property 'send' of undefined "

Does anyone have any idea how to resolve it. 
We havent updated any of our dependencies in a while.

**Comment by scholtzm** [comment]
Can you provide stack trace?

**Comment by Clickplaycorp** [comment]
what is stack trace?

**Comment by jwigley** [comment]
http://stackoverflow.com/questions/2923858/how-to-print-a-stack-trace-in-node-js

**Comment by blanko18** [comment]
TypeError: Cannot read property 'send' of undefined
at SteamClient._send (/app/node_modules/steam/lib/steam_client.js:75:19)
at ClientRequest.<anonymous> (/app/node_modules/steam/lib/handlers/user.js:113:12)
at ClientRequest.g (events.js:260:16)
at emitOne (events.js:77:13)
at ClientRequest.emit (events.js:169:7)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
at TLSSocket.socketOnData (_http_client.js:305:20)
at emitOne (events.js:77:13)
at TLSSocket.emit (events.js:169:7)

**Comment by scholtzm** [comment]
Are you using latest node-steam?

**Comment by blanko18** [comment]
"name": "steam-tradeoffers",
  "version": "0.2.0",
  "private": true,
  "dependencies": {
    "request": "2.27.0",
    "cheerio": "*",
    "long": "*",
    "express": "4.8.5",
    "socket.io" : "1.0.6",
    "underscore" : "1.6.0",
    "winston" : "0.7.3",
    "steam" : "0.6.x",
    "body-parser" : "~1.0.1",
    "forever" : "~0.11.1",
    "mysql" : "2.4.x",
    "express-myconnection" : "1.x.x",
    "steam" : "0.x.x",
    "node-localstorage" : "0.5.x"
  }

**Comment by blanko18** [comment]
thats my dependencies

**Comment by scholtzm** [comment]
I see `steam` twice. Either way, you are running outdated version. Carefully update to 1.x and see if the issue persists.

**Comment by blanko18** [comment]
hi thanks for your comment can you point me in the right direction? im a newbie with node js anf its been a while since i got the code we have been using it for a few months now and thought that it would be ok to use it as it is as it had been working ok,  but now we have been having issues with memory leaks
