### ISSUE TITLE
IF user send a few items, bot accepts them and adds to the database the duplicates

### ISSUE THREAD

**Issue by BlackOnix** [steam-forward/node-steam-forum#109]
Hello friend. I had a problem
If user from my site send a few items in one trade, bot accepts them and adds to the database the duplicates
For example:
User send a AK-47 | Redline, Negev | Army Sheen and AWP | Redline.Only three weapon.
Bot accept this trade. But in log and in database bot added duplicates of items

Log:
AK-47 | Redline (Field-Tested)(299.64599999999996) October 26, 2015 9:20 PM
AWP | Redline (Field-Tested)(299.64599999999996) October 26, 2015 9:20 PM
AK-47 | Redline (Field-Tested)(299.64599999999996) October 26, 2015 9:20 PM
AWP | Redline (Field-Tested)(455.88599999999997) October 26, 2015 9:20 PM
AWP | Redline (Field-Tested)(455.88599999999997) October 26, 2015 9:20 PM
Negev | Army Sheen (Minimal Wear)(2.2319999999999998) October 26, 2015 9:20 PM
AWP | Redline (Field-Tested)(299.64599999999996) October 26, 2015 9:20 PM
AWP | Redline (Field-Tested)(455.88599999999997) October 26, 2015 9:20 PM

Code:
```javascript
offers.loadPartnerInventory({partnerSteamId: offer.steamid_other, appId: 730, contextId: 2, tradeOfferId: offer.tradeofferid, language: "en"}, function(err, hitems) {
							if(err) {
								steam.webLogOn(function(newCookie) {
									offers.setup({
										sessionID: globalSessionID,
										webCookie: newCookie
									}, function(err) {
										if (err) {
										}
									});
								});
								recheck = true;
								return;
							}
							var items = offer.items_to_receive;
							var wgg=[],num=0;
							for (var i = 0; i < items.length; i++) {
								for(var j=0; j < hitems.length; j++) {
									if(items[i].assetid == hitems[j].id) {
										wgg[num] = hitems[j];
										num++;
										break;
									}
								}
							}
```

**Comment by dragonbanshee** [comment]
Don't ask help for code you didn't write. It won't help you.

**Comment by andrewda** [comment]
What @dragonbanshee said. Leaked code is a pain in the butt to fix and it'll be much easier to make a bot yourself.

**Comment by BlackOnix** [comment]
I know that this code is not mine, but the deadline running out of work. Please help me

**Comment by andrewda** [comment]
@BlackOnix We're not here to fix issues with your leaked code. 

When you say deadline, I can only hope that you did not accept work without knowing how to program a bot.
