### ISSUE TITLE
How to check if offer matches specific object

### ISSUE THREAD

**Issue by dragonbanshee** [steam-forward/node-steam-forum#11]
So lets say I have an object (this would correspond to what I want the offer to look like)
```javascript
var itemsFromMe = ['Mann Co. Supply Crate Key', 'Refined Metal'];
var itemsFromThem = ['Base Grade Key'];

if(offer.items_to_give === itemsFromMe && offer.items_to_receive === itemsFromThem) {
    offers.acceptOffer(id, callback);
```

How can I see if a specific trade offer matches an array/object of items which I define, since I can't use item names (I don't think)?

**Comment by jhartzell** [comment]
You need to match the items by either original_id or by classid and instanceid as the asset id's changes once they are accepted into your inventory from a trade offer.

**Comment by dragonbanshee** [comment]
@jhartzell so do originalid and classid not change then, and they are always the same for each item? Like Mann Co. keys are 109 or something? I thought that those changed, the only thing that was constant was the defindex.

**Comment by jhartzell** [comment]
As far as classid changing I can't say 100%, however I have not yet seen it change for cs:go. original_id will never change, this is a static identifier for every item upon creation, this is how bank sites can track owner history of an item.

**Comment by dragonbanshee** [comment]
Oh that makes sense, but what you're saying is that o can't say "if the trade contains these items" then accept?

**Comment by scholtzm** [comment]
Of course you can do that. The example you provided on the top is 100% doable and fairly easy to implement.

Regarding `classid`s, they **do** change.

**Comment by dragonbanshee** [comment]
@scholtzm glad to hear that it's possible, as trade offer bots wouldn't be good without them, but how would I implement this without knowing the item ids in advance?

**Comment by scholtzm** [comment]
You would use the item names, not IDs.

**Comment by dragonbanshee** [comment]
That worked perfectly for me. +1 to you.
