### ISSUE TITLE
Getting a list of my inventory (with assetids and item names)?

### ISSUE THREAD

**Issue by charredgrass** [steam-forward/node-steam-forum#111]
I'm using [node-steam-tradeoffers](https://github.com/Alex7Kom/node-steam-tradeoffers).

The bot I'm trying to write reads received trades and determines what items are in it, accepting if it matches certain criteria.

Currently, it gets the assetids of the items in the trade and tries to match it to a name (to figure out what the item is) by scanning the bot and other user's inventories. The problem I'm running into is getting the inventories, since the `loadMyInventory` and `loadPartnerInventory` functions have callbacks, which make it really hard for me to use that information outside the callback function.

What's the best way to do this? Nothing I try seems to work, I can't make the synchronous functions wait for the asynchronous ones.

**Comment by andrewda** [comment]
Why would you need to use it outside of the callback? Put your code [i]inside[/i] of the callback.

**Comment by Alex7Kom** [comment]
@charredgrass In your particular case .getOffers (and Steam WebAPI underlying it) accepts `get_descriptions` options, see #81, so you probably don't need to load inventories, but...
In general, you should learn how JS works (see the forum README), so you'll be able to control async flow in your code.
