### ISSUE TITLE
Running Multiple Bots using a Master/Slave structure.

### ISSUE THREAD

**Issue by dnowitski69** [steam-forward/node-steam-forum#112]
We are trying to figure out the best way to set up the structure for our project.

Ultimately we would like 100 bots online processing the same tasks using some sort of job queue.

We were thinking about having a master.js assigning tasks to slave.js.

Master would poll a db to fetch jobs and send the task to a specific slave.

Slave would receive job, complete task, and callback master.

We'd like to use node-cluster for balancing the load of the Master file.

Anyone care to shine some light on which node modules we should be using to accomplish such task? What's the best way for Master and Slave to send/receive data? Do we process the bot logins and trade functions in one file? Or should we log in all the bots in one file and process the trades function in another?

Thank you for your help!

**Comment by andrewda** [comment]
How about [node-steam-parentbot](https://github.com/dragonbanshee/node-steam-parentbot)? If you don't want to use something like that, it's not too difficult to code your own.
