### ISSUE TITLE
Socket timed out

### ISSUE THREAD

**Issue by spyrek10** [steam-forward/node-steam-forum#114]
Hello,
I have problem with my bot connecting to steam CM servers.
The bot was working fine until today. Today I was editing few things and I was using two different bot accounts. Everything was ok, bots were logging successfully, but after few hours my VPS(from OVH) cannot connect to the steam CM servers.
Looks like banned IP, but I don't know why. 

Logs:
connecting to 146.66.152.15:27018
socket timed out
socket closed
connecting to 72.165.61.188:27018
socket timed out
socket closed
connecting to 146.66.152.14:27018
socket timed out
socket closed

**Comment by scholtzm** [comment]
Looks like Steam was being Steam.
