### ISSUE TITLE
Counter offer problem

### ISSUE THREAD

**Issue by matrix14** [steam-forward/node-steam-forum#116]
Hi, i have problem:
1. Player choose items to withdraw, my bot send to he an offer.
2. Player do a counter offer.
3. Item from my bot goes to player/

I don't have anywhere a trade in which I traded item with player, but I only have it in Trades history.

http://scr.hu/0gr/l54lv -> status 4 is offer countered
http://scr.hu/0gr/496gg -> it's from trades history, you see, someone give that item and after few minutes he withdraw it.
http://scr.hu/0gr/qtrst -> it's trade sent from my bot, it countered.
http://scr.hu/0gr/e5ye3 -> counter offer with "Missing items/items no longer available to trade"

I don't have anywhere in my bot .acceptOffer and I can't accept it... I don't know what happend...

**Comment by dragonbanshee** [comment]
Can you show us some code, or else we can't help you.

**Comment by matrix14** [comment]
Ok, I try to show the code later, because I'm in school now. But I Think, it's steam problem or in my train of though. Steam says that offer is countered (state 4, and when i check it now, it state 4 too), but offer is done (i don't have this items and second user have this items).

**Comment by matrix14** [comment]
`(function(ii) {
				offers.getOffer ({
					"tradeOfferId": waitingWithdraw[ii][0]
				}, function(err, response) {
					if (err) {
						console.log(getTimeStamp()+'ERR: checkAwaitingWithdraw TradeId: '+tradeId+' ERR:'+err);
						//Do nothing
						console.log(getTimeStamp()+'ERROR> checkAwaitingWithdraw2 ERR:'+err);
					} else {

						var tradeId = response.response.offer.tradeofferid;
						var offerState = response.response.offer.trade_offer_state;
						var tradeIdFromSucTrade = response.response.offer.tradeid;
						
						if(offerState==3) { //Accepted
							//Items withdrawed, items is removing from user deposit on my page
						} else if(offerState==4) { //Countered
							//Backing items to player deposit on my page
						} else if(offerState==5) { //Expired
							//Backing items to player deposit on my page
						} else if(offerState==7||offerState==10) { //Decline
							//Backing items to player deposit on my page
						} else if(offerState==6||offerState==8) { //Decline
							//Backing items to player deposit on my page
						} else if(offerState==2||offerState==9) { //Waiting for response, or not email confirmed
							//Do nothing
						} else { //Do nothing }
					}
				});
			})(i);`
