### ISSUE TITLE
How to load market_hash_name?

### ISSUE THREAD

**Issue by denis-marecky** [steam-forward/node-steam-forum#117]
Can somebody give me example, how to get market_hash_name from rgDescriptions, using node-steam-tradeoffers?

**Comment by scholtzm** [comment]
Load an inventory. Each item in the result will have `market_hash_name` property. That's it.

**Comment by denis-marecky** [comment]
item.market_hasn_name not working.

**Comment by andrewda** [comment]
`console.log(item);`

What does this output?

**Comment by denis-marecky** [comment]
In csgo json structure, market_hash_name is in rgDescriptions, so I get only appid, contexid, assetid, classid, instanceid, amount.

**Comment by scholtzm** [comment]
node-steam-tradeoffers [merges items with their descriptions](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/index.js#L354). You shouldn't need to do anything special there.

**Comment by denis-marecky** [comment]
I saw this, but console.log(item.market_hash_name) give me undefined

**Comment by denis-marecky** [comment]
I understand the problem. Items were loaded using CEcon_TradeOffer and CEcon_Asset. And now is the question, how to load market_hash_name in best way
