### ISSUE TITLE
Error 403 

### ISSUE THREAD

**Issue by ArnaudDassy** [steam-forward/node-steam-forum#118]
I regenerated my Api Key but nothing changed. Any solutions guys ? Does the domain name important ? I defined it as localhost. The error occurs when I load my inventory. I'm using the trade offer example script.

**Comment by scholtzm** [comment]
Loading inventory does not require API key so that's probably not it.

Also mentioning which package you are using is pretty important.

**Comment by ArnaudDassy** [comment]
![capture](https://cloud.githubusercontent.com/assets/11327936/11072660/1ae1364a-87e7-11e5-8942-ffb70822b059.PNG)

Here's my document.

**Comment by ArnaudDassy** [comment]
Problem solved, family mode was enabled !
