### ISSUE TITLE
Nove v0.10.40

### ISSUE THREAD

**Issue by bulgakovk** [steam-forward/node-steam-forum#119]
Hello, here's my question : Is it possible to run offerbot.js (https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/offerbot.js) on my server with node 0.10.40 version? I tried to use steam@0.6.8, but got this:
>/root/bot.js:32
>var steamUser = new Steam.SteamUser(steamClient);
>                           ^
>TypeError: undefined is not a function

Some advices?

**Comment by scholtzm** [comment]
> Some advices?

Update node.

You could use [outdated code](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/bec517d07d131d46713e15e908bd219b990f4da7/examples/offerbot.js) with outdated libraries but that just makes no sense.

**Comment by dragonbanshee** [comment]
If you are using steam 0.6.8, there is no `SteamUser`, everything is just on `SteamClient`. You should update node to the newest version and use Steam 1.x.x if possible.

**Comment by bulgakovk** [comment]
I can't update node to the newest version because I'm using meteor-up to deploy my meteor.js application. It doesn't work with new versons of Node, but I found compromise by using node@0.12.0 and steam@1.0.0. Meteor deploying and steam bot now work fine. Thanks.
