### ISSUE TITLE
tradeofferid - dont work for me

### ISSUE THREAD

**Issue by AnegvE** [steam-forward/node-steam-forum#12]
[node-steam-tradeoffers]
if ( offer.items_to_give !== undefined
        || offer.items_to_receive === undefined
        || offer.trade_offer_state !== 2 )
    {
        console.log('TRADE FALSE');
        offers.declineOffer({tradeOfferId: offer.tradeofferid});
    }else{
        console.log('TRADE TRUE');        
        offers.acceptOffer({tradeOfferId: offer.tradeofferid});        
    }

offers.declineOffer() work perfect, 
but offers.acceptOffer() not work and
var tradeId = parseInt(offer.tradeofferid, 10);
steam.respondToTrade(tradeId, true);
also not working and no error messages.
Accept and send offer I can in https://steamcommunity.com.
Please, can help me.

**Comment by scholtzm** [comment]
`respondToTrade` is for "live" trades only. Don't bother with that.

**Comment by AnegvE** [comment]
Thank, scholtzm.
I received an error [Error: There was an error accepting this trade offer.  Please try again later. (24)]
I see You discussed it before, but cannot find the solution.
Can you tell me what to do?

**Comment by AnegvE** [comment]
I see https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd
InsufficientPrivilege = 24;
What does it mean?
What should I do?

**Comment by scholtzm** [comment]
SteamGuard perhaps.

**Comment by AnegvE** [comment]
Anyway, thank you. Good luck
