### ISSUE TITLE
Sending a offer error

### ISSUE THREAD

**Issue by OMGGDOG** [steam-forward/node-steam-forum#124]
So i get this error everytime "Cannot read property '0' of undefined" i send my bot a offer.

**Comment by andrewda** [comment]
Well the error is pretty self-explanatory. You're trying to get the 0 property of an undefined variable. As you didn't provide any code, my guess is that you're using the leaked CSGOFast code and this is a MySQL error. Either way, this doesn't really belong here.

**Comment by OMGGDOG** [comment]
I fixed it myself.

**Comment by OMGGDOG** [comment]
Quiet easy fix.
