### ISSUE TITLE
Escrow

### ISSUE THREAD

**Issue by feedarz** [steam-forward/node-steam-forum#125]
According this ss https://mckay.media/r9gzg Valve is gonna add new security features. Sending and accepting offer is no longer possible since they gonna use mobile confirmation.

Do you guys have any info how to make bots now?

**Comment by scholtzm** [comment]
Calm down, the feature has not been enabled yet. No one knows the details of how it's going to work, no need to jump the gun.

> how to make bots now?

Just like before.

**Comment by feedarz** [comment]
Okay, thanks for fast response. But i saw some articles about escrow_expire_date response from getOffer function. I was asking here because you may know about api changes. Anyway thanks.

**Comment by scholtzm** [comment]
Most info (which isn't much) can be found [here](https://www.reddit.com/r/Steam/comments/3tdpfd/valve_to_add_escrow_to_trading_which_holds_items/).
