### ISSUE TITLE
Sending items to the non-friend user. makeOffer error (15) 

### ISSUE THREAD

**Issue by Krash-ua** [steam-forward/node-steam-forum#126]
Hi. Could you pleaze tell me how to send items to the non-friend user? 
```javascript
offers.makeOffer ({
            partnerSteamId: '76561198074482505',
            itemsFromMe: [],
            itemsFromThem: [ {
            appid: 570,
            contextid: 2,
            amount: 1,
            assetid: '7349799823',
            accessToken: 'U0ZI2_IL' }],
            message: 'test message'
        }, function(err, response) { 

});
```

I have hardcoded all the data. Could you pleaze tell me what is wrong?
The user is not my friend. The token is correct but I still get an error 15 on making an offer.

**Comment by scholtzm** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers#makeofferoptions-callback

> `accessToken` (optional) is a token from the public Trade URL of the partner

**Comment by Krash-ua** [comment]
Thank you scholtzm, could you pleaze take a look again?(I have changed my question).  Do you have any ideas whats wrong?

**Comment by scholtzm** [comment]
You made the `accessToken` part of your `itemsFromThem` array.

```js
assetid: '7349799823',
accessToken: 'U0ZI2_IL' }], // <-- this is wrong
```

**Comment by Krash-ua** [comment]
Omg, thank you, that was a really stupid mistake))
