### ISSUE TITLE
webauthentification error 403 retrying

### ISSUE THREAD

**Issue by AlexPlayin** [steam-forward/node-steam-forum#127]
Hi.

I'm receiving the 403 error everytime the bot starts and while it is running. 
I already regenerated the steam api key twice and also check for family sharing off.
I dont know whats the problem. Account isn't limited but under 15 days cooldown for trading and stuff.

here are my libraries:
![screenshot_3](https://cloud.githubusercontent.com/assets/15946328/11306838/95bab0f6-8fb4-11e5-98db-31a4e0b1dba4.png)

Thank you for your help.

**Comment by scholtzm** [comment]
You won't be able to trade if your account is in the cooldown period.

**Comment by AlexPlayin** [comment]
So is that the reason for the 403 authenticfication error?

**Comment by scholtzm** [comment]
You'd have to provide some technical info.

**Comment by AlexPlayin** [comment]
Such as?

System: 8.1 Windows
Node Version: Newest stable build
API key is made for localhost for testing.

**Comment by scholtzm** [comment]
Like when exactly it happens, code snippets etc.

**Comment by AlexPlayin** [comment]
I can't say in which Snippet the error happends since the bot is not fully crashing. He still answers my commands and is also shown as online in steam. The error message is shown every 5 -10 seconds or so and gets slower the longer the bot runs for some reason. Because there are no working breakpoints in notepad++ i can't say where the error happens.

**Comment by scholtzm** [comment]
You didn't write the code, did you?

**Comment by AlexPlayin** [comment]
Partly. The main code was written by someone else but i rewrote parts of it. I used that template due to the reason that i'm not familiar with the request lib.

**Comment by AlexPlayin** [comment]
Ok so i have figured out the the cookie refreshing is the source of the error.

This is the code where he reloads it.


else if(message.indexOf("/show") == 0) {
			var params = message.split(' ');
			offers.loadMyInventory({
				appId: 730,
				contextId: 2
			}, function(err, items) {
				if(err) {
					steam.sendMessage(steamID, 'Inventory could not be loaded. Try again later.');
					steam.webLogOn(function(newCookie) {
						offers.setup({
							sessionID: globalSessionID,
							webCookie: newCookie
						}, function(err) {
							if (err) {
							}
						});
					});
					return;

How do i refresh the cookies like the FAQ page says?

Sorry for not posting for so long.
