### ISSUE TITLE
steam-node no reponse

### ISSUE THREAD

**Issue by stackbasher** [steam-forward/node-steam-forum#128]
Hello guys
I tried to write a steambot and id didn't worked. atm i entred "node xyz.js" in the console, nothing happened. So i tried to use an example, wrote by Alex7Kom. And again the same. The link to the example: https://gist.github.com/Alex7Kom/d764ef2925060c4e7c27.
if i do "node donation_bot.js", nothing happens. Not even "logged in!" is popping up in the cmd. There is no reponse, just a cursor wich is blinking, wich is saying me that the script is running. im not even getting an error code. after like 30 seconds the script stops. i don't even get an error code. im pretty sad right now. does anyone know what im doing wrong?

**Comment by scholtzm** [comment]
Did you edit the top part?

**Comment by stackbasher** [comment]
the name and password? yes i did ;D

**Comment by scholtzm** [comment]
Did you read the instructions?

**Comment by stackbasher** [comment]
if you mean those instructions, then yes ;D 

1    Install the latest Node.js.
 2   Click 'Download ZIP' button on the right of this page.
 3   Unpack this ZIP file wherever you like.
 4   Switch to the resulting directory in a command line or a terminal.
 8   Do npm install in the directory.
 9   Edit donation_bot.js to put your account credentials. Leave authCode as is for now.
  10  Run node donation_bot.js. It will 'crash' shortly, and you'll receive an email with Steam Guard code.
 11   Edit donation_bot.js again to put Steam Guard code into authCode, then run node donation_bot.js again. A sentry file will be created in the same directory with the bot. From now on you can run node donation_bot.js to launch the bot.


Are threre any other instructions?

**Comment by jwigley** [comment]
Have you tried adding in some debugging so you see how far it's getting?

**Comment by stackbasher** [comment]
well, just the events aren't getting fired. stuff like this doesn't work: 

steamClient.on('connected', function() {
  steamUser.logOn(logOnOptions);
});

im at work now, so i cant test anything. maybe my firewall is blocking the connection >_>

**Comment by stackbasher** [comment]
im back at home now. the firewall didn't blocked anything. But i just tried to debug the 'steam_client.js' file and i saw, that it tries to connect on and on. Im getting the following error: "socket timed out".
Does someone know what is blocking my connection to the steam servers? I CAN rech servers like google.com with my node script. 
Maybe ive got an old servers.js. Does someone knows some ips of the steamservers?

**Comment by scholtzm** [comment]
Are you sitting behind a proxy or something like that?

**Comment by stackbasher** [comment]
no, i don't use any proxy. but im trying to setup the boot on another system now. ;D

**Comment by stackbasher** [comment]
lol, it just connected with the server "72.165.61.174:27018". Every other server semms not to reply ^^

**Comment by stackbasher** [comment]
it connects now, but the event still wont getting fired ^^

**Comment by stackbasher** [comment]
Thank you all for your help. i didn't found the issue, but it works perfectly on a Server. 

#Closed
