### ISSUE TITLE
Steam trade holds

### ISSUE THREAD

**Issue by vejbuch** [steam-forward/node-steam-forum#129]
Helo,
how to fix this https://support.steampowered.com/kb_article.php?ref=8078-TPHC-6195&auth=43ec81a6c20ed06dd10fa46719820a21 ??

Thanks

**Comment by scholtzm** [comment]
There is no "complete" solution as of yet.

**Comment by vejbuch** [comment]
So it will not be able to use the boot for jackpot? Or another solution?

**Comment by feedarz** [comment]
Please dont close this topic, i ll follow it to watch for solutions

**Comment by scholtzm** [comment]
[Everything related to Escrow can be found in this single post.](https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/)

**Comment by vejbuch** [comment]
Hello, please lock

**Comment by vejbuch** [comment]
Please lock

**Comment by andrewda** [comment]
@vejbuch You can close the issue yourself with the "Close Issue" button next to "Comment" below the new comment text box. The issue does not need to be locked.
