### ISSUE TITLE
making offer

### ISSUE THREAD

**Issue by feedarz** [steam-forward/node-steam-forum#13]
Hello. I am attempting to use setInterval() and mysql query to fetch items`s assetids, user`s steamid and his token and then make trade offer with fetched items. I am getting Error (26) or Error 401. Any answers would help me.

Here is my part of the code.
http://pastebin.com/AkfetBf4

**Comment by jhartzell** [comment]
I would also love to hear some feedback on this! I am experiencing the same issue.

**Comment by jhartzell** [comment]
This 401 error was resolved for me, I was passing an invalid sessionId into setup(), I had a typo on a variable name :)

**Comment by feedarz** [comment]
Its now over, but i have new kind of problem. Using this code i am trying to send offer, that i am store in db in name/name/name format(name = market_name). And if i have multiple instances of the same item, i can`t accept offer cuz of Error(2).

Here is the code http://pastebin.com/vCpvdE20

Please help guys!!

**Comment by feedarz** [comment]
Now its solved!

**Comment by dragonbanshee** [comment]
@Alex7Kom please close this, since it's solved
