### ISSUE TITLE
Notify when user accpets bot's trade offer

### ISSUE THREAD

**Issue by naksuasd** [steam-forward/node-steam-forum#130]
Hi! Is there any way to check / notify bot when user accepts trade offer that bot sent?

Thanks in advance.

**Comment by scholtzm** [comment]
You can check the trade status and that's about it.

**Comment by naksuasd** [comment]
You mean looping trade status for example with async library?

**Comment by scholtzm** [comment]
The library shouldn't be necessary but otherwise yes.
