### ISSUE TITLE
Force Logon

### ISSUE THREAD

**Issue by blanko18** [steam-forward/node-steam-forum#133]
Do you guys have any idea how i can force a re-logon of a specific bot without having to restart the bot app itself.

As per my testing of  the bot app i sometimes encounter the 401 error for a single bot account when that happens no matter how many times i try i always encounter the same error.
But when i restart my bot app i no longer experience that issue. 

I would like to avoid restarting my bot app and instead a force re-logon for that specific bot account.
Can anyone help me?

Thank you

**Comment by shaunidiot** [comment]
Use forever to restart your script automatically. Else, catch the http error code, disconnect the bot and connect again. 

https://github.com/foreverjs/forever
