### ISSUE TITLE
Escrow 2fa and Sentry files

### ISSUE THREAD

**Issue by dolanmiu** [steam-forward/node-steam-forum#134]
I came across this:

https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/

And I quote:

```
Your account needs to use mobile authenticator and 2FA (2-factor auth). This bypasses sentry file and the only way to log into your account is by providing 2FA code every single time you log in.
```

What will happen to sentry files? Will they remain as they are?

If so, do you guys recommend switching from using sentry files into using the mobile 2fa? or staying with the sentry files?

**Comment by scholtzm** [comment]
"Sentry file might be still necessary to bypass the 7 day trade lock."

**Comment by dolanmiu** [comment]
So what do they mean when they say:

```
This bypasses sentry file
```

**Comment by scholtzm** [comment]
It means that even if you provide `sha_sentryfile` when logging in, you will still have to enter the 2FA auth code.

**Comment by blanko18** [comment]
how do you enter the 2fa auth code on login using the code?

**Comment by jwigley** [comment]
> how do you enter the 2fa auth code on login using the code?

`two_factor_code`
It's clearly documented. https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon

**Comment by blanko18** [comment]
thank you
