### ISSUE TITLE
node-steam's SteamUser vs node-steam-user

### ISSUE THREAD

**Issue by dolanmiu** [steam-forward/node-steam-forum#136]
What is the difference between:

https://github.com/seishun/node-steam/tree/master/lib/handlers/user

and:

@DoctorMcKay's node-steam-user?

https://www.npmjs.com/package/steam-user

I quote from node-steam-user:

> The node-steam module installation used by SteamUser. You can use this in place of require('steam') if you'd like to avoid duplicate installations.

But from what I can see, @seishun's ```node-steam``` does not include ```node-steam-user``` as a dependancy anywhere lol

```node-steam-user``` seems more feature rich, especially with the trade hold implementations. Should I use that instead?

**Comment by DoctorMcKay** [comment]
node-steam-user is basically an alternative node-steam SteamUser handler. As you say, it's much more feature rich.

I disagreed with making *everything* a separate handler. For that reason, node-steam-user includes all the SteamFriends and SteamTrading handler functionality within itself.

**Comment by dolanmiu** [comment]
I was trying to use your ```node-steam-user``` instead of ```SteamUser``` and having lots of trouble. 

It doesn't really fit in ```node-steam```?

In your examples, it does not use ```node-steam```

the ```client``` object is a ```new SteamUser()```

https://github.com/DoctorMcKay/node-steam-user/blob/master/examples/basicbot.js

whereas in node-steam, the ```client``` is a ```new Steam.SteamClient();```
then steamUser is a ```new Steam.SteamUser(steamClient);``` (consuming the ```client```)

I REALLY don't want to have to rewrite if I were to use ```node-steam-user```

**Comment by DoctorMcKay** [comment]
node-steam-user's API isn't compatible with node-steam's SteamUser API.

node-steam-user can automatically create a SteamClient, or you can provide one. Example:

```js
var Steam = require('steam');
var SteamUser = require('steam-user');

var steamUser = new SteamUser();
var client = steamUser.client; // this is a Steam.SteamClient

var client2 = new Steam.SteamClient();
var steamUser2 = new SteamUser(client2); // this is using client2 as its SteamClient
```

**Comment by dolanmiu** [comment]
Right, so refering to the ```basicbot.js``` example:

Should I do:

```
var client = new Steam.SteamClient();
var steamUser = new SteamUser(client); // this is using client as its SteamClient

client.connect();

client.on('connected', function () {
    loginBlob.create(botDocument, authCode).then(function (logOnOptions) {
        steamUser.logOn(logOnOptions);
    });
});

steamUser.on('loggedOn', function(details) {
	console.log("Logged into Steam as " + client.steamID.getSteam3RenderedID());
	client.setPersona(SteamUser.Steam.EPersonaState.Online);
	client.gamesPlayed(440);
});
```

That is what I have currently, but it throws an error:

```
events.js:215
    throw TypeError('listener must be a function');
          ^
TypeError: listener must be a function
    at TypeError (native)
    at SteamClient.removeListener (events.js:215:11)
    at SteamUser.logOff.SteamUser.disconnect (C:\Users\dolan\GitHub\bot-manager\node_modules\steam-user\components\logon.js:149:14)
    at SteamUser._handlers.(anonymous function) (C:\Users\dolan\GitHub\bot-manager\node_modules\steam-user\components\logon.js:253:9)
    at SteamUser._handleMessage (C:\Users\dolan\GitHub\bot-manager\node_modules\steam-user\components\messages.js:160:29)
    at SteamClient.emit (events.js:118:17)
    at SteamClient._netMsgReceived (C:\Users\dolan\GitHub\bot-manager\node_modules\steam\lib\steam_client.js:172:10)
    at Connection.emit (events.js:107:17)
    at Connection._readPacket (C:\Users\dolan\GitHub\bot-manager\node_modules\steam\lib\connection.js:50:8)
    at Connection.emit (events.js:104:17)
    at emitReadable_ (_stream_readable.js:424:10)
    at emitReadable (_stream_readable.js:418:7)
    at readableAddChunk (_stream_readable.js:174:11)
    at Connection.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by DoctorMcKay** [comment]
node-steam-user will handle connecting the client for you. You only need to call logOn.

**Comment by dolanmiu** [comment]
Then what is the purpose of ```node-steam``` client if ```node-steam-user``` already deals with that?

I use 3 libraries:
node-steam
steam-tradeoffers
steam-user

does ```steam-user``` have trade offer functionality?

**Comment by DoctorMcKay** [comment]
There really isn't a purpose. You only need to provide the SteamClient if you want to, but I don't know why you would. node-steam-user handles it itself.

The only trade offer functionality that node-steam-user has is the [`tradeOffers`](https://github.com/DoctorMcKay/node-steam-user#tradeoffers) event.

**Comment by dolanmiu** [comment]
I need more than just a ```tradeOffers``` event, it needs to send and receive trades, I guess I must use:

[node-steam-tradeoffers](https://github.com/Alex7Kom/node-steam-tradeoffers)

But I am afraid that your library and @Alex7Kom's library would be incompatible...

Ok, a third option would be your ```steamcommunity``` module

Why is there duplicate functionality in ```node-steam-user``` and ```steamcommunity```?

do they both do the same thing? I am confused

**Comment by scholtzm** [comment]
There's a difference between Steam's network protocol and Steam's HTTP APIs. If there's a duplicate functionality, it still does it differently.

node-steam is a low level library for Steam's network protocol.
node-steam-user is a feature rich wrapper around node-steam.

node-steamcommunity deals with steamcommunity.com.
node-steam-tradeoffers and node-steam-tradeoffer-manager deal exclusively with trade offers.

**Comment by dolanmiu** [comment]
I see, that makes a lot more sense.

I am using [```node-steam-weblogon```](https://github.com/Alex7Kom/node-steam-weblogon) at the moment for connecting to steam community, but it seems [```node-steamcommunity```](https://github.com/DoctorMcKay/node-steamcommunity) is superior.

I can't seem to get ```node-steam-weblogon``` to work after switching over to ```node-steam-user```

Should I just switch over to ```node-steamcommunity```?

What are your thoughts?

**Comment by scholtzm** [comment]
node-steam-user already provides node-steam-weblogon's functionality. Just listen to [`webSession event`](https://github.com/DoctorMcKay/node-steam-user#websession).

**Comment by dolanmiu** [comment]
But I am saying ```node-steam-weblogon``` is redundant because I quote:

> webLogOn(callback)

> Logs into Steam Community

Doesn't ```node-steamcommunity``` do that anyway?

Oh and for some reason, I do not get the ```webSession``` event. My code is straight from the example:

```
steamUser.on('webSession', function (sessionID, cookies) {
        console.log("Got web session");
        // Do something with these cookies if you wish
    });
```

**Comment by scholtzm** [comment]
webSession is emitted after logging in with SteamUser.

**Comment by dolanmiu** [comment]
I have tried all I can, it is not being emitted:

```
var steamUser = new SteamUser(),
        bot = {
            user: steamUser,
            offers: new SteamTradeOffers(), //atm its used to get inventory and gets offers when a 'client' trade event happens. Will use it for handing out trade offers 
            info: botDocument
        },
        deferred = Q.defer();

    loginBlob.create(botDocument, authCode).then(function (logOnOptions) {
        steamUser.logOn(logOnOptions);
    });

    steamUser.on('error', function (err) {
        console.error("Error occurred on steamClient:");
        console.error(err);
    });

    steamUser.on('loggedOn', function (logonResp) {
        console.log("Logged into Steam as " + steamUser.steamID.getSteam3RenderedID());
        steamUser.setPersona(SteamUser.Steam.EPersonaState.Online);
    });

    steamUser.on('webSession', function (sessionID, cookies) {
        console.log("Got web session");
        // Do something with these cookies if you wish
    });
```

Is there anything wrong with this code?

**Comment by DoctorMcKay** [comment]
That looks fine. It's logging in successfully?

**Comment by dolanmiu** [comment]
Yes, it is logging in perfectly

```
Automatically creating bot
Attempting to create login blob with sentry file
Automatically creating bot
Attempting to create login blob with sentry file
Found sentry file
Found sentry file
Logged into Steam as [a:1:188721]
Logged in bot
Logon Success
Logged into Steam as [a:1:298161]
Logged in bot
Logon Success
```

No webSession message

**Comment by DoctorMcKay** [comment]
Your login object is malformed. You've logged in anonymously.

**Comment by dolanmiu** [comment]
Ok the reason was is because I used ```account_name```, instead of ```accountName``` because ```node-steam``` wanted that.

```
{ accountName: 'XXX',
  password: 'XXX',
  sha_sentryfile: <Buffer 9f a8 1a 96 3c 42 99 8f 84 a6 58 0c 0f 42 8f e9 38 ec 17 12> }
Found sentry file
{ accountName: 'XXX',
  password: 'XXX',
  sha_sentryfile: <Buffer 61 ea bc f6 3e f2 e1 57 e5 43 0b cb c6 7c 4b 10 46 36 f2 05> }
```
Is there anything wrong with this?

I get 
```
Steam Guard Code: Unhandled message: 1
```

Perhaps sha_sentryfile should be shaSentryfile?

**Comment by DoctorMcKay** [comment]
Don't put the sentryfile in the logon object. Call `user.setSentry()` instead.

**Comment by dolanmiu** [comment]
Will do, will take some time.

So you wasn't kidding when you said these libraries are incompatible

**Comment by dolanmiu** [comment]
Thanks, it works great now

**Comment by scholtzm** [comment]
If you just read the docs, you would know all of this.
