### ISSUE TITLE
Mobile authentication

### ISSUE THREAD

**Issue by Jallvar** [steam-forward/node-steam-forum#139]
Hello. I'm from Russia, and therefore do not speak English.
Guys, save.
Is there a solution for node.js, mobile authorization.

**Comment by andrewda** [comment]
Yes.

https://github.com/DoctorMcKay/node-steamcommunity
https://github.com/DoctorMcKay/node-steam-totp

should be all you need

**Comment by Jallvar** [comment]
Thank you, and there are some examples.
I apologize in advance.

**Comment by blanko18** [comment]
@andrewda how can you use that with nodesteamtradeoffers?
sorry but im new with nodejs

**Comment by andrewda** [comment]
You have a few options when using node-steamcommunity. You can either confirm all trades that go into mobile confirmation, which is easier but less secure, or you can have your bot individually confirm trades, checking their tradeOfferIds as it confirms. For the sake of explaining this, I'll just go with the confirmation of all trades.

First, after setting the cookies using node-steamcommunity's `setCookies()` method, you'll need to call [`startConfirmationChecker(interval, identity_secret)`](https://github.com/DoctorMcKay/node-steamcommunity/wiki/Steam-Confirmation-Polling#startconfirmationcheckerpollinterval-identitysecret), where interval is the time between each check in milliseconds and identity_secret is, obviously, your identity_secret code (documentation linked). After calling this, all trades will be automatically accepted via mobile confirmation.

**Comment by panp858** [comment]
@andrewda Thank you for your post. I'm stuck with the identity_secret part. I've enabled the mobile thing a while ago and I'm wondering where I can get a identity_secret when I enabled the twofac days ago?

The seconds question is about checking each outstanding conformations. So if I want to get all conformations which are in the queue atm I need to call getConfirmations(time, key, callback) right?  dont get the parameter key, do I have to create one before I call this method? After that I've to call respondToConfirmation for each open conformation.

**Comment by scholtzm** [comment]
> I'm wondering where I can get a identity_secret when I enabled the twofac days ago?

How did you enable it? If by using the mobile app, the key is locked inside your device but it's possible to retrieve it: http://forums.backpack.tf/index.php?/topic/45995-guide-how-to-get-your-shared-secret-from-ios-device-steam-mobile/

The second part is explained in the README: https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getconfirmationstime-key-callback

**Comment by Jallvar** [comment]
I have shared_code of steam guard (mobile) file.
I enter the codes obtained from steam-totp, he wrote that wrong.

**Comment by Nikoly0072** [comment]
Должен должен быть base64 строка

**Comment by Jallvar** [comment]
мне теперь этот shared_code в base64 конвертировать?

**Comment by Nikoly0072** [comment]
Нет эта сторока должна быть уже в base64

**Comment by lparamonov** [comment]
I still didn't get how to log in steam by using node-steamcommunity. (I'm new in node js) could anyone share some piece of code how to log in in steam, please? 
actually, I tried this way:
var fs = require('fs');
var Steam = require('steam');

// if we've saved a server list, use it
if (fs.existsSync('servers')) {
  Steam.servers = JSON.parse(fs.readFileSync('servers'));
}

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);

var sentryfile;
if(fs.existsSync('sentryfile.' + 'username' + '.hash')) {
    sentryfile = fs.readFileSync('sentryfile.' + 'username' + '.hash');
}

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: '',
    password: '',
	auth_code : ''
  });
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult == Steam.EResult.OK) {
    console.log('Logged in!');
  }
  else {
   console.log('Not Logged in!');
  }
});

however, it throws
er; // Unhandled 'error' event
