### ISSUE TITLE
Is it possible to use steam@0.6.8 and the new version of steam-tradeoffers?

### ISSUE THREAD

**Issue by darknegative** [steam-forward/node-steam-forum#140]
If yes how? Becase when i'm trying to install the newest version of steam-tradeoffers bot starts but when ever i sent a trade offer or recieve one bot give's me error 403

**Comment by scholtzm** [comment]
It should work just like before.

**Comment by darknegative** [comment]
But there is an issue. 

[12:8:34:451] Message: "TradeOffer: 910129122 FROM: Admin"
accepting offer: There was an error accepting this trade offer.  Please try again later. (24)
accepting offer: There was an error accepting this trade offer.  Please try again later. (24)
[12:8:37:942] Message: "Next function is acceptOffer! - 76561198203422414 - 910119017"


If i use the newest version i'm getting that error. Any ideas whats wrong?

I also added that 

offers.setup({
			sessionID: currentSessionId,
			webCookie: newCookie,
                APIKey: config.apiKey
		}, 
 on WebLogOn
