### ISSUE TITLE
Error: Logon fail: 85

### ISSUE THREAD

**Issue by blanko18** [steam-forward/node-steam-forum#141]
when i turned on the mobile authenticator setting on my bot account i got this error

**Comment by scholtzm** [comment]
Yep, that's correct behavior.

**Comment by blanko18** [comment]
how do i fix it? are the sentries useless now?

**Comment by scholtzm** [comment]
You fix it by providing the 2FA code. And no they are not.

**Comment by blanko18** [comment]
thanks
