### ISSUE TITLE
Login fail 5 with escrow

### ISSUE THREAD

**Issue by dragonbanshee** [steam-forward/node-steam-forum#142]
I keep trying to login my bot to enable 2fa on my server, but I keep getting error code 5. Waiting did not help. Anyone know how to fix?

**Comment by emdy** [comment]
@dragonbanshee show your problem(pic).

**Comment by dragonbanshee** [comment]
I actually just fixed this, but it was because I was getting blocked from logging in since steam is limiting logins.
