### ISSUE TITLE
Can somebody help ? (Nodejs steam-tradeoffer syntax error)

### ISSUE THREAD

**Issue by darknegative** [steam-forward/node-steam-forum#143]
Anyidea what exacly i'm missing here?

http://pastebin.com/rjT1HmzK

What i'm trying to do is if the user doesnt use mobile then it cancel it. But i think i havent put a  } in the right place. 

Can somebody tell me where i'm wrong on that code?

**Comment by jwigley** [comment]
This isn't really the place for discussing general JavaScript syntax errors. This forum is for discussing issues with using node steam libraries.

Anyway, there is multiple closing brackets missing. Properly formatting and commenting your code will make it a lot easier to debug. If you're lazy, just run it through a JavaScript beautifier.

Correct code is probably something like this (although I haven't tested it):
```javascript
var accepOff = function(offer, retry, callback) {
    offer.getEscrowDuration(function(err, daysTheirEscrow, daysMyEscrow) {
        if (err) console.log(err);
        else {
            if (daysTheirEscrow != 0) {
                offer.decline(function(err) {
                    if (err) console.log(err);
                });
            } else {
                offers.acceptOffer({
                    tradeOfferId: offer.tradeofferid
                }, function(err, log) {
                    if (err) {
                        helper.msg(err);
                        if (retry > 0) {
                            retry--;
                            setTimeout(accepOff(offer, retry, callback), 2000);
                        } else {
                            return callback(false);
                        }
                    } else {
                        helper.msg('AcceptTrade #' + offer.tradeofferid);
                        return callback(true);
                    }
                }); //acceptOffer

            } //daysTheirEscrow
        } //err
    }); // getEscrowDuration
};
```

**Comment by scholtzm** [comment]
You couldn't have possibly written any of that code yourself if you can't tell where the syntax error is. Especially since it even tells you which line causes the error.

**Comment by darknegative** [comment]
Thank you it worked. I'm sorry i didnt knew that it should be in that forum i thought i could ask. Sorry for the miss understand. Issue can close now.
