### ISSUE TITLE
Help delaying trade offer to next pot

### ISSUE THREAD

**Issue by danifantom** [steam-forward/node-steam-forum#146]
Im using steam-tradeoffers to handle the offers in my jackpot website, im my database i have set the pot status(ready, closed, finished). I must make the bot only accept the "deposit" when the pot status is "ready", otherwise it should be delayed until it is ready.
Here's my little peace of code for this:

    if (potState!='ready') {
       offers.declineOffer({tradeOfferId: offer.tradeofferid}); 
       console.log('Offer declined, pot is not ready...');
       return;
    }
So what I'm doing currently is declining the offers, because if i just "return" the function, the other functions related to the offer will either accept or decline it. How can I change that so the offer stays "on hold" and gets accepted as soon the next pot is ready?
Thank You very much!

**Comment by jwigley** [comment]
Rather than decline the offers, maybe build up a list of offers to accept later. 
Then when the next pot is ready, loop through the list and accept them.

**Comment by danifantom** [comment]
But the problem is i can't put the offers on hold, the other conditions checking handle it. E.g:
Let's say i have these 2 conditions checkers

`if (potState!='ready') {}`
`if (itemWanted=='true') {}`

Doesn't matter what I do with the first if, if I don't decline or accept the offer, it will be procesed on the second if and will be either declined or accepted. What should I do?

**Comment by jwigley** [comment]
Sounds like you need to nest the condition statements.
```js
if (potState!='ready') {
  if (itemWanted=='true') { ... }
}
```

or check them together?

```js
if (potState!='ready' && itemWanted=='true') { ... }
```

Side note:  looks like `itemWanted` is a string with the word 'true' in it. Hard to tell from just that code, but it might be better as a boolean true/false.

**Comment by danifantom** [comment]
Its so many condition statements with so many functions in it, cant nest them all. Is there another way maybe?

**Comment by jwigley** [comment]
Then it sounds like you need to restructure/refactor your code.
There's nothing in `steam-tradeoffers` that can really help you with a logic/structural issue like this. It just provides the trade interface, how you use it is up to you.

**Comment by danifantom** [comment]
Yeah, thank you! You made me realize that my code is all wrong, although its working.
Instead of like:

    if (potState!='ready') {
       //decline
    }
    if (itemWanted=='true') {
       //decline
    }

I should do:

    if (potState!='ready') {
       //decline
    }else{
       if (itemWanted=='true') {
          //decline
       }
    }
    

It'll work, right? I hope so cause i started coding it already xD

**Comment by jwigley** [comment]
From your code above you will decline in the following 2 cases:
- pot is not ready 
- pot is ready and itemWanted is true

Hard to tell without understanding how the rest of it works, if the above is what you really want. Either way you're probably on the right track now.

Good luck.

**Comment by danifantom** [comment]
Yeah thats what I want. I didnt notice that failure in my code. Now you cleared my mind, thank You very much
