### ISSUE TITLE
Help with steam-tradeoffers

### ISSUE THREAD

**Issue by deepsh4h** [steam-forward/node-steam-forum#148]
So, I have updated the package steam-tradeoffers to the latest version in order to use the function "getTradeHoldDuration(options, callback)"

Also added APIKey in 

    offers.setup({
			sessionID: currentSessionID,
			webCookie: newCookie,
			APIKey : myAPIKey
    }

Before updating steam-tradeoffers the bot was able to detect any tradeoffers, but after updating it the bot does nothing. (Won't even detect any incoming trade offers)

What am I missing ?

**Comment by jwigley** [comment]
What code do you have in place to detect new trade offers? Did you also update to the latest node-steam?

[storehouse.js](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/storehouse.js) has a good example of detecting and accepting new offers.

**Comment by officialdeep** [comment]
No I am using steam@0.6.8

I guess the latest node-steam requires NodeJS 4.x

**Comment by jwigley** [comment]
> No I am using steam@0.6.8

Well the newer `steam-tradeoffers` should still work ok with 0.6.8, but just take note that example I linked to you is based on the latest node-steam.

**Comment by officialdeep** [comment]
Yes, thanks.

Close this issue now.
