### ISSUE TITLE
Making offer Error(2)

### ISSUE THREAD

**Issue by feedarz** [steam-forward/node-steam-forum#15]
Its now over, but i have new kind of problem. Using this code i am trying to send offer, that i am store in db in name/name/name format(name = market_name). And if i have multiple instances of the same item, i can`t accept offer cuz of Error(2).

Here is the code http://pastebin.com/vCpvdE20

Please help guys!!

**Comment by feedarz** [comment]
Solved!

**Comment by dragonbanshee** [comment]
@feedarz if this is solved, you should close the issue

**Comment by spyrek10** [comment]
Can you tell how did you solve it?
I have the same problem.

**Comment by feedarz** [comment]
@spyrek10 i thought that if you use item with value(how much you want to put in offer) you are actually trying to send the same items x value times. Every item has unique id that if multiplied in trade by x value times makes trade not acceptable.
