### ISSUE TITLE
Zero error response when getOffers

### ISSUE THREAD

**Issue by feedarz** [steam-forward/node-steam-forum#152]
When i am trying to getOffers i recieve this error: 
"{}" (yes, thats all)

I am using the latest versions of steam, steam-tradeoffers, steam-weblogon, steam-totp, steam-web-api-key, steamcommunity-mobile-confirmations

**Comment by Aareksio** [comment]
The error object should be `request` error object, if you get empty object, mostly likely there's something wrong with your code.

Make sure you use the function properly:

```js
offers.getOffers({
    get_received_offers: 1,
    active_only: 1,
    time_historical_cutoff: Math.round(Date.now() / 1000)
  }, function(error, body) {
    if (
      body
      && body.response
      && body.response.trade_offers_received
    ) {
      body.response.trade_offers_received.forEach(function(offer) {
        if (offer.trade_offer_state === 2) {
          if (offer.steamid_other === admin) {
            offers.acceptOffer({tradeOfferId: offer.tradeofferid});
          } else {
            offers.declineOffer({tradeOfferId: offer.tradeofferid});
          }
        }
      });
    }
  });
```
[(Source)](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/storehouse.js#L72)

If that didn't help you may paste your code here.

**Comment by feedarz** [comment]
function handleOffers() {
    offers.getOffers({
        get_received_offers: 1,
        active_only: 1
    }, function(error, body) {
        if (
            body
            && body.response
            && body.response.trade_offers_received
        ) {
            body.response.trade_offers_received.forEach(function(offer) {
                if (offer.trade_offer_state == 2) {
                    if(is_checkingOfferExists(offer.tradeofferid)) return;

                    if(offer.items_to_give != null && config.admin == offer.steamid_other) {
                        console.tag('SteamBot', 'TradeOffer').log('TRADE OFFER #' + offer.tradeofferid + ' FROM: Admin ' + offer.steamid_other);
                        offers.acceptOffer({tradeOfferId: offer.tradeofferid});
                        confirmTimer = setInterval(function(){confirmTrade();},5000);
                        return;
                    }
                    if(offer.items_to_give != null) {
                        offers.declineOffer({tradeOfferId: offer.tradeofferid});
                        return;
                    }
					console.log(offer.steamid_other);
					console.log(offer.accessToken);
                    
					offers.getTradeHoldDuration({tradeOfferId : offer.tradeofferid}, function(err, response){
                        var escrow = false;
                        if (!response || (response && typeof response.their === 'undefined') || response.their != 0){
                            offers.declineOffer({tradeOfferId: offer.tradeofferid});
							console.log('РћР±РјРµРЅ РѕС‚РєР»РѕРЅС‘РЅ РїРѕС‚РѕРјСѓ С‡С‚Рѕ РЅРµС‚ escrow!');
                            escrow = true;
                            return;
                        }
						
                    if (offer.items_to_receive != null && offer.items_to_give == null && !escrow) {
                        checkingOffers.push(offer.tradeofferid);
                        console.tag('SteamBot', 'TradeOffer').log('TRADE OFFER #' + offer.tradeofferid + ' FROM: ' + offer.steamid_other);
                        redisClient.multi([
                            ['rpush', redisChannels.tradeoffersList, offer.tradeofferid],
                            ['rpush', redisChannels.checkItemsList, JSON.stringify(offer)],
                            ['rpush', redisChannels.usersQueue, offer.steamid_other]
                        ]).exec(function(){
                            redisClient.lrange(redisChannels.usersQueue, 0, -1, function(err, queues) {
                                io.sockets.emit('queue', queues);
                            });
                        });
                        return;
                    }});
                }
            });
        }
    });
}

steamUser.on('tradeOffers', function(number) {
    if (number > 0) {
        handleOffers();
    }
});

**Comment by Aareksio** [comment]
Make sure the bot has any offer active, then check what's returning `getOffers()` callback - log the `error` and the `body`.

**Comment by feedarz** [comment]
handleOffers is being executed only if new trade offer come up.
```javascript
steamUser.on('tradeOffers', function(number) {
    if (number > 0) {
        handleOffers();
    }
});
```
 Error returning {}, body returning undefined. Its really strange, because there are like 6 trades on the bot.

**Comment by andrewda** [comment]
Wait. Error is returning `{}` and body is returning `undefined`? I would have guessed it would be the opposite...

**Comment by feedarz** [comment]
@andrewda yes it is.

**Comment by dragonbanshee** [comment]
How do you know what `error` is and what `body` is? It doesn't look like it is logging it anywhere...
