### ISSUE TITLE
ItemsFromThem: jsonarray

### ISSUE THREAD

**Issue by ghost** [steam-forward/node-steam-forum#155]
So I have the asset ids in an array. e.g: assetid[0] = 'item asset id here' etc. and I don't know from the start the exact numbers of asset ids there are. So I want a piece of code that gets the array of asset ids(all are from appid: 730 and amount: 1 and contextid: 2 I guess idrk what contextid is) and then send a trade offer in which the partner offers the items in the array.

**Comment by bulgakovk** [comment]
You need to get partner inventory in JSON and parse it I guess.
