### ISSUE TITLE
Steam trade offers with 2FA

### ISSUE THREAD

**Issue by Dezash** [steam-forward/node-steam-forum#157]
Is there a node module that would support sending an offer to someone and also use the 2FA so there is no hold for the trade? I have already setup 2FA login with node-steam module but trade offers are left without 2FA support. I've tried looking into node-steam-trade and node-steam-tradeoffers but seems like they don't support it.

**Comment by Aareksio** [comment]
Check [node-steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity) - [manual](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#getconfirmationstime-key-callback) or [automatic](https://github.com/DoctorMcKay/node-steamcommunity/wiki/Steam-Confirmation-Polling#startconfirmationcheckerpollinterval-identitysecret) way.

**Comment by pranaymk** [comment]
https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/
