### ISSUE TITLE
Bot won't accept tradeoffer when using new node-steam-tradeoffers. Crashes when using old.

### ISSUE THREAD

**Issue by piotrlis** [steam-forward/node-steam-forum#160]
Hello github :)

Bot can see new offer, and try to check trade hold duration (returns undefined anyway, but that is another problem) (node-steam-tradeoffers 3.x):

http://i.imgur.com/vSBPdf7.png

But then nothing happens, my offer is neither declined or accepted...

When using old version of module (node-steam-tradeoffers 2.x) bot is trying to accept (checks price, checking min deposit) but crashes after it.

My question is, what should i change in my bot comparing to old module to use it with new version of module (3.x) ?
I hope you understand my problem as my english is not very good :dart:

**Comment by jensej** [comment]
Do you have 2FA enable?

**Comment by piotrlis** [comment]
Thanks for your reply.

I have 2FA enabled on my BOT account and i see verification code in node console every 30 sec.

**Comment by piotrlis** [comment]
It works perfectly with old node-steam-tradeoffers module and no getTradeHoldDuration option

http://i.imgur.com/LHEHYvQ.png

**Comment by piotrlis** [comment]
Everything works perfectly after ~4 months of using 2.2.0 version. Thanks!
