### ISSUE TITLE
There was an error sending your trade offer.  Please try again later. (8)

### ISSUE THREAD

**Issue by Dezash** [steam-forward/node-steam-forum#162]
I'm getting this error when I call makeOffer() function from node-steam-tradeoffers module:
'There was an error sending your trade offer.  Please try again later. (8)'
```
if (itemscopy[x].tradable && (itemscopy[x].market_name).indexOf(sendItems[j]) == 0) {
	sendItems[j] = "FASGASFHGASFHGFasdasdasd";
	item[num] = {
		appid: 730,
		contextid: 2,
		amount: 1,
		'assetid': itemscopy[x].id
	}
		num++;
	}
	if (num > 0) {
			//console.log('Tradebot: PartnerSteamId='+row[i].userid);
			//console.log('Tradebot: itemsFromMe='+item);
			//console.log('Tradebot: accessToken='+row[i].token);
		offers.makeOffer ({
			partnerSteamId: row[i].userid,
			itemsFromMe: item,
			accessToken: row[i].token,
			itemsFromThem: [],
			message: 'automated trade'
		}, function(err, response){
			if (err) {
				console.log('Tradebot: '+err);
				return;
			}
```
I logged steam ID, items and access token. They all seem to be correct. I tried capitalizing appId and contextId but that didn't help either.
What could be wrong?

**Comment by andrewda** [comment]
`'assetid': itemscopy[x].id`

Why is assetid in quotes here, but appid, contextid, and amount aren't? Also, this is leaked code. You'll be much better off re-making the bot completely, as the leaked code has TONS of issues.

**Comment by Dezash** [comment]
I read that assetid should be a string somewhere. Anyway, both variants assetid and 'assetid' don't work. Also I did pretty much remake the whole bot. This is the last part.

**Comment by andrewda** [comment]
You heard correctly, the assetid should be a string. You're making the property a string, which really doesn't matter. If `itemscopy[x].id` is an integer, you should be doing this instead:

```
item[num] = {
    appid: 730,
    contextid: 2,
    amount: 1,
    assetid: itemscopy[x].id.toString()
}
```

**Comment by Dezash** [comment]
Stringified it but still the same error pops up :/

**Comment by Dezash** [comment]
Turns out it was because the bot was sending 2 of the same item. Is tradeoffers module not able to do that or is it something wrong with my code?

**Comment by andrewda** [comment]
No, it's not possible to send the same item multiple times. `node-steam-tradeoffers` does not have detection of these items built in, as it's supposed to be a minimalist wrapper for Steam tradeoffers. However, `node-steam-tradeoffer-manager` does have this feature built in.
