### ISSUE TITLE
You cannot trade with XXX. (50)

### ISSUE THREAD

**Issue by BlackOnix** [steam-forward/node-steam-forum#163]
Please guys, help me. When i try send weapon, i get the error 50

Error: There was an error sending your trade offer. Please try again later.

You cannot trade with XXX. (50)

**Comment by andrewda** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/76

https://github.com/Alex7Kom/node-steam-tradeoffers/issues/182

**Comment by BlackOnix** [comment]
I exit everywhere.
I use the token to send weapon.
I'm sure it took 7 days

**Comment by mihayy5** [comment]
It can be cause API is down?
Look CS:GO's API is down: https://steamgaug.es/ [Right now: 4:50 14.02.2016 (UTC+02:00)]
