### ISSUE TITLE
Steam disabled trade offers confirmation opt-out

### ISSUE THREAD

**Issue by sck-v** [steam-forward/node-steam-forum#164]
`As part of our push to increase account security, you can no longer opt out of trade and Market confirmations. To complete a trade, trade offer, or Market listing, you'll need to confirm that action via a Steam email sent to ....`

Any way to automate it?

**Comment by andrewda** [comment]
Please use Google / the search bar here / http://reddit.com/r/SteamBot. This has been answered a quadrillion times.
