### ISSUE TITLE
node-steam-tradeoffers: cannot load partner's inventory

### ISSUE THREAD

**Issue by CodeLuca** [steam-forward/node-steam-forum#169]
Null is returned?
```
      Bot.offers.loadPartnerInventory({
        'partnerSteamId': offer.steamid_other,
        'appId': '730',
        'contextId': '2'
      }, function(partnerItems) {
        // partnerItems.forEach(function( partnerItem) {
          console.log(partnerItems);
        // });
      });
```

**Comment by CodeLuca** [comment]
@Alex7Kom

**Comment by CodeLuca** [comment]
More in depth look at code:
https://gist.github.com/CodeLuca/632f9c893a1f15b4678a

**Comment by andrewda** [comment]
Taken directly from the docs of node-steam-tradeoffers:

>If success the *second* argument to callback will be an array of item objects and the third argument will contain raw inventory objects

**Comment by CodeLuca** [comment]
oh god. *facedesk*
