### ISSUE TITLE
[Error: There was an error sending your trade offer. Please try again later. (26)]

### ISSUE THREAD

**Issue by madlybong** [steam-forward/node-steam-forum#170]
Ok I've half working code right now ... If i trade to bot account (node steam still running) from friends account via browser, bot auto accepts the offer and everything is fine ...

but when i do the same thing from makeOffer it gives me this error

[Error: There was an error sending your trade offer. Please try again later. (26)]

ex. 1

```
{ partnerSteamId: '765611980********',
  itemsFromMe:
   [ { appid: 570,
       contextid: 2,
       amount: 1,
       assetid: '136107323_230139020' },
     { appid: 570,
       contextid: 2,
       amount: 1,
       assetid: '161240980_230139020' } ] }
```
ex. 2

```
{ partnerSteamId: '765611982********',
  accessToken: '****',
  itemsFromMe: [ { appid: 570, contextid: 2, amount: 1, assetid: '370181842_0' } ],
  itemsFromThem: [] }
```

**Comment by jwigley** [comment]
You need itemsFromThem, even if it's empty.

```
 itemsFromThem: [],
```

**Comment by madlybong** [comment]
@jwigley look at my **ex. 2** I've already tried it ... same error occurs ...

**Comment by jwigley** [comment]
ah sorry. I misread your post and thought ex. 2 was an example of it working.

Can you post the code where you are making the offer? How are you getting the asset id? Have you verified it's correct?

**Comment by madlybong** [comment]
@jwigley Mostly hand coded ... i double checked with my assetid and loadPartnerInventory values they are okay ... 
tycast assetid to string ----> **Okay**
trade able / marketable -----> **Yes**
bot steam guard or anything like that -----> **No**
load inventory (own / partner / non friend) -----> **working**
steam market in browser trade to bot -----> **Working**
my website to bot account -----> **_error [(26)]_**

i'm just lost here ... please help ...

**Comment by jwigley** [comment]
Without any code to look at all I can give is some generic debugging advice. Hopefully still of some use though!

- Try comparing your code with the [offerbot example](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/offerbot.js). Can you see any differences between what it's doing and your code? Perhaps try plugging in the example's loadInv / makeOffer section into your code. Make sure it works, then work backwards from there.

- Try [debugging](https://github.com/request/request#debugging) the actual request that gets sent. Compare it with a correct request.

- Check previous [error 26 discussions](https://github.com/steam-forward/node-steam-forum/issues?utf8=%E2%9C%93&q=is%3Aissue+error+26+) for hints.

**Comment by madlybong** [comment]
Trying my best to compare things ... every thing is similar like the example ... 

My debug msg ---->

```
{ partnerSteamId: '765611982******',
  accessToken: 'u_z*****',
  itemsFromMe: [ { appid: 570, contextid: 2, amount: 1, assetid: '7768839950' } ],
  itemsFromThem: [],
  message: 'test' }
[Error: There was an error sending your trade offer.  Please try again later. (26)]

```
what is wrong here, please ???

**Comment by andrewda** [comment]
For me, error 26 usually appears when the specified assetid is not in my inventory. You are trying to send Dota 2 items, correct?
