### ISSUE TITLE
Problem with getOffers

### ISSUE THREAD

**Issue by Jallvar** [steam-forward/node-steam-forum#171]
Problem. not in the list of my offer.
the standard code. already experimented with time.
but he never showed up.
Display full list.
ID also offers no
I tried to search by author, also

```
function CheckOffer() {
  offers.getOffers({
    get_received_offers: 1,
    active_only: 1,
    time_historical_cutoff: Math.round(Date.now() / 1000)
  }, function(error, body) {
    if(body.response.trade_offers_received) {
      body.response.trade_offers_received.forEach(function(offer) {
          if(offer.steamid_other == '76561198002252743')
          console.log(offer);
          }
        }
      });
    }
  });
}
```

**Comment by andrewda** [comment]
I don't understand your issue, please try to be more clear. What's not working? What have you tried?

**Comment by Jallvar** [comment]
I posted a trade.
getOffer it no

**Comment by jwigley** [comment]
Is `error` empty?
Is `body` empty?

Does it find some trade offers but not the one you sent? Or does it never find any offers at all?

**Comment by Jallvar** [comment]
error empty
I come my trades. but it is not present, my. sent. and on a site it is
