### ISSUE TITLE
[Tutorial] Getting market_hash_names and the values of items within a tradeoffer.

### ISSUE THREAD

**Issue by iJamesPHP** [steam-forward/node-steam-forum#176]
Later today when I'm home from college I'll be posting my very primitive method for getting all the information on items within a tradeoffer, I saw that some people were having issues doing this and so was I but I've got a very simple but effective way of doing it!

**Comment by CodeLuca** [comment]
AWESOME!

**Comment by CodeLuca** [comment]
updates?

**Comment by CodeLuca** [comment]
*cough*

**Comment by Alex7Kom** [comment]
@CodeLuca Please stop bumping the issue.
