### ISSUE TITLE
Getting 26 errors on makeOffer call

### ISSUE THREAD

**Issue by ArsenyYankovsky** [steam-forward/node-steam-forum#18]
Hey guys. I'm getting these type of errors
`[Error: There was an error sending your trade offer.  Please try again later. (26)]`

every time I try to send a trade offer. I don't have a trade ban or something like that on my acc, I waited more than 7 days and I can accept offers from other people, I just can't send them. This is how my opts param currently looks like:
```
{
   "partnerSteamId":"76561198028082712",
   "itemsFromMe":[
      {
         "appid":570,
         "contextid":2,
         "amount":1,
         "assetid":"6805779725"
      },
      {
         "appid":570,
         "contextid":1,
         "amount":1,
         "assetid":"6805779704"
      }
   ],
   "accessToken":"4Pc7KhfC",
   "itemsFromThem":[

   ]
}
```

Any ideas? Thanks in advance.

**Comment by AardvarkMike** [comment]
Did you check previous issues?

I'm sure a couple of days ago someone had the same issue and it's down to capitalisation of appId.

**Comment by ArsenyYankovsky** [comment]
Yes I did, and it seems like a guy who posted it somehow figured his stuff out. Unfortunately he didn't post his solution or a root of the problem.

**Comment by ArsenyYankovsky** [comment]
Ok, it seems like the problem was me using asset id instead of id coming from loadMyInventory method. Any Idea on how do I know that THIS item from tradeoffer is THIS in my inventory besides classid? Thanks.

**Comment by AardvarkMike** [comment]
You should use getItems() rather than the data that comes with the trade offer.

That way you have the correct item ID and you know you have the items.
