### ISSUE TITLE
acceptOffer problem

### ISSUE THREAD

**Issue by bercik809** [steam-forward/node-steam-forum#19]
Hello,

I've used an acceptOffer, but i have error 'there was an error accepting this trade offer. please try again later. (24)'. What can I do?

**Comment by scholtzm** [comment]
SteamGuard most likely.

**Comment by bercik809** [comment]
What do you mean? Because I can decline offers but i can't accept offers only.

**Comment by bercik809** [comment]
I have sha sentry;

**Comment by scholtzm** [comment]
It takes ~7 days for the computer to be verified. You can't accept trade offers during this period.

`decline` uses official Steam API, `accept` does not and is limited by the SteamGuard.
