### ISSUE TITLE
Cant run the script.

### ISSUE THREAD

**Issue by darknegative** [steam-forward/node-steam-forum#21]
Hello. So I'm trying to install Node-Steam on my pc but its not works.

I have node.js v.0.12.5
Python 27
Windows 7 Pro 64bit
Net. Framework 4.5

And when i run the example (I edited the username and password) this happens.

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation. All rights reserved.

C:\Users\DNA>cd desktop

C:\Users\DNA\Desktop>mkdir sapila

C:\Users\DNA\Desktop>cd sapila

C:\Users\DNA\Desktop\sapila>npm install steam
steam@0.6.8 node_modules\steam
├── buffer-crc32@0.2.5
├── adm-zip@0.4.7
├── bytebuffer@4.0.0 (bufferview@1.0.1, long@2.2.5)
└── protobufjs@4.0.0 (ascli@1.0.0, glob@5.0.12, yargs@3.14.0)

C:\Users\DNA\Desktop\sapila>cd steam
The system cannot find the path specified.

C:\Users\DNA\Desktop\sapila>cd C:\Users\DNA\Desktop\sapila\node_modules\steam

C:\Users\DNA\Desktop\sapila\node_modules\steam>node example.js

C:\Users\DNA\Desktop\sapila\node_modules\steam>node -v
v0.12.5

when i do node example.js nothing happens

the PATH is set like that

C:\Program Files\nodejs;C:\Users\DNA\AppData\Roaming\npm;C:\Python27\

Any idea whats happening? Thanks

**Comment by darknegative** [comment]
Bump

**Comment by dragonbanshee** [comment]
What do you mean nothing happens? Does the process just end instantly.

**Comment by darknegative** [comment]
its end instantly.

The problem is when i run the script i do node example.js and its not do anything. For example

C:\Users\DNA\Desktop\sapila\node_modules\steam>node example.js (I press enter and after 1 sec it skip it)
C:\Users\DNA\Desktop\sapila\node_modules\steam>
