### ISSUE TITLE
Error: There was an error sending your trade offer. Please try again later. (8)

### ISSUE THREAD

**Issue by mikelsx** [steam-forward/node-steam-forum#22]
i have this function:

`function makeOffer(source, botItemOffer, theirItemOffer, message) {`

    offers.makeOffer({
        partnerSteamId: source,
        itemsFromMe   : botItemOffer,
        itemsFromThem : theirItemOffer,
        message       : message
    }, function (error, object) {
        if (error === null) {
            logger.info("Trade offer sent to  " + source + " Trade offer id: " + object.tradeofferid);
        } else {
            logger.info("Error in created trade offer: " + error);
        }
    });
`}`
and i call it like this:
`makeOffer("76561198026511719",'[{"appid": 730,"contextid": 2,"amount": 1,"assetid": 1282139309}]',"[]","automated trade offer");`
the item is in my inventory and is tradable, what's wrong? 
Error 8 mean a param is wrong but i dont really know what could be wrong there? ._.

**Comment by scholtzm** [comment]
Why is `botItemsOffer` enclosed in ' ?
