### ISSUE TITLE
Error: There was an error sending your trade offer.  Please try again later. (8)

### ISSUE THREAD

**Issue by CodeLuca** [steam-forward/node-steam-forum#244]
App.Bot.offers.makeOffer({
      partnerSteamId: user,
      accessToken: req.params.token,
      itemsFromMe: [{
        'appid': 730,
        'contextId': 2,
        'amount': 1,
        'assetid': item
      }],
      itemsFromThem: [],
      message: 'Thanks for using TripleSkins.com'
    }, function(offerid) {
      debug(offerid);
      res.send(offerid);
    });

I dont know what I'm doing wrong :/

**Comment by CodeLuca** [comment]
@Alex7Kom

**Comment by CodeLuca** [comment]
I realise in the callback its meant to be the second parameter that give the offerid. I have changed this now, still stuck with the same problem though.

**Comment by CodeLuca** [comment]
App.Bot.offers.makeOffer({
      partnerSteamId: '76561198185469317',
      itemsFromMe: [{
        'appid': 730,
        'contextId': 2,
        'amount': 1,
        'assetid': '188530139'
      }],
      itemsFromThem: []
    }, function(err, offerid) {
      debug(err);
      res.send(offerid);
    });

substituted all the values in.

**Comment by andrewda** [comment]
`contextId` should be `contextid`
