### ISSUE TITLE
Easy sentry file generator

### ISSUE THREAD

**Issue by pmk010** [steam-forward/node-steam-forum#25]
Think a few people would find this helpful and I don't know where to put it, feel free to move/delete as appropriate if I've put it in the wrong place.

Enter the username, password and steam guard code at the relevant prompts. The file is named the same as the username.

```
var username;
var password;
var steamCode;

var Steam = require("steam");
var fs = require("fs");
var readline = require("readline");

var steam = new Steam.SteamClient();

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question("Username: ", function(answer) {
	username = answer;
	rl.question("Password: ", function(answer2) {
		password = answer2;
		rl.pause();
		steam.logOn({
			accountName: username,
			password: password
		});
	});
});

steam.on("loggedOn", function(result) {
	console.log("Logged in");
    steam.setPersonaState(Steam.EPersonaState.Online);
    steam.setPersonaName(username);
	setTimeout (function() {
		process.exit();
	}, 10000);
});

steam.on("error", function(error) {
	if (error.cause == "logonFail") {
		if (error.eresult == 63) {
			rl.resume();
			rl.question("Steam guard code: ", function(answer) {
				steamCode = answer;
				rl.close();
				steam.logOn({
					accountName: username,
					password: password,
					authCode: steamCode
				});
			});
		} else {
			console.log("Logon fail: " + error.eresult);
		};
	};
});

steam.on('sentry', function(data) {
	var format = "sentry_ " + username;
	fs.writeFileSync(format, data);
	console.log("Sentry file successfully saved!");
});
```

(For another purpose - reddit /u/-rocky-)

**Comment by MajorErection** [comment]
You might have to update it since I don't think this works anymore

**Comment by andrewda** [comment]
@MajorErection It shouldn't be that hard to update. If you really need it, I could probably update it when I get back home.

**Comment by pmk010** [comment]
I edited it a little as it turns out steam needs a bit of time to validate the sentry buffer after providing it to you. I'll try to update it to work with v1+ in a bit, I just haven't updated from v0.6.8 as I don't currently see a need to.

**Comment by evanode** [comment]
or 
client.on('sentry', function(data) {
    require('fs').writeFileSync('sentry_' + logOnOptions['accountName'] + '.hash', data);
});
