### ISSUE TITLE
Why do I get: Error: There was an error sending your trade offer.  Please try again later. (15)?

### ISSUE THREAD

**Issue by CodeLuca** [steam-forward/node-steam-forum#250]
Hey,
After extensive research for 3 days straight I cannot seem to find any way to fix this error. At first I thought it was the steam error 15 which is that the partner's inventory is full but this wasnt the case. I have since then been researching everywhere including here and on node-steam-tradeoffers to see if there was anyone with a similar problem.

I found that it was to do with the fact that the accessToken was incorrect. I spent a long time making sure everything was correct and I cannot find any problems with this code that would cause an error. I have substituted the variables in my code for you to see an example:

```
    App.Bot.offers.makeOffer({
      partnerSteamId: '76561198177942969',
      accessToken: 'K9F2DR-E',
      itemsFromMe: [{
        'appid': 730,
        'contextid': 2,
        'amount': 1,
        'assetid': '5707019199'
      }],
      itemsFromThem: []
    }, function(err, offerid) {
```

To add to the puzzle, this code was working for 24 hours straight and then for some reason all offers got this error, although I hadn't changed the code.

Please comment if you think there is an error of with the code, thanks :)

@Alex7Kom @andrewda

**Comment by Alex7Kom** [comment]
Just [a brief search](https://github.com/steam-forward/node-steam-forum/issues?q=is%3Aissue+15+is%3Aclosed) shows that an error 15 is most likely an access token issue. I tried to construct [a link](https://steamcommunity.com/tradeoffer/new/?partner=217677241&token=K9F2DR-E) from the offer data you provided, and it is indeed expired.

**Comment by CodeLuca** [comment]
@Alex7Kom I'm aware that the issue was to do with access tokens as I described, and thanks for constructing that link, but I seem to get this error with every partner I try.

**Comment by CodeLuca** [comment]
@Alex7Kom I'll find another example

**Comment by CodeLuca** [comment]
@Alex7Kom  https://steamcommunity.com/tradeoffer/new/?partner=261009964&token=nQAMyET_ for instance, this person has a valid trade link, yet I get the same error.

**Comment by CodeLuca** [comment]
@Alex7Kom any ideas?
