### ISSUE TITLE
Error: missing required parameter

### ISSUE THREAD

**Issue by CodeLuca** [steam-forward/node-steam-forum#253]
bot has been working fine for 2 weeks and for some reason now I get these errors on the vast majority of my trades, any ideas?

```
  api_receive Error: missing required parameter
    at SteamTradeOffers.<anonymous> (/root/tripleskinsbot/node_modules/steam-tradeoffers/index.js:412:23)
    at Request.self.callback (/root/tripleskinsbot/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/root/tripleskinsbot/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/root/tripleskinsbot/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7) +0ms
```

And then this is my code to accept the trade:

`App.Bot.offers.acceptOffer({tradeOfferId: tradeofferid}, function(err) {
`

**Comment by CodeLuca** [comment]
@andrewda @Alex7Kom

**Comment by Aareksio** [comment]
Missing semicolon in 1417 line.

Seriously, code, used modules, stacktrace?

**Comment by CodeLuca** [comment]
I'll provide it when I'm home, I thought it would be something more like I'm logged in from somewhere else which caused the error or something since the code was running fine for 2-3 weeks. 

Friday, 22 April 2016, 15:49 +0100 from notifications@github.com  <notifications@github.com>:

**Comment by CodeLuca** [comment]
@Aareksio 
```
  api_receive Error: missing required parameter
    at SteamTradeOffers.<anonymous> (/root/tripleskinsbot/node_modules/steam-tradeoffers/index.js:412:23)
    at Request.self.callback (/root/tripleskinsbot/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/root/tripleskinsbot/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/root/tripleskinsbot/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7) +0ms
```

And then this is my code to accept the trade:

`    App.Bot.offers.acceptOffer({tradeOfferId: tradeofferid}, function(err) {
`

Some trades work some don't, but this whole error is new and has never happened before the last 48 hours.

**Comment by CodeLuca** [comment]
@andrewda @Alex7Kom

**Comment by CodeLuca** [comment]
bump

**Comment by Alex7Kom** [comment]
Most likely the error occurs on inventory load, since stack trace points at `mergeObjects()` function which used to merge parts of the inventory. So to fix this we need to know what is wrong with inventory on which the error occurs.

**Comment by CodeLuca** [comment]
@Alex7Kom What's the easiest way of getting that information to you, also do you think this could be effected by steam's servers. They have been going up and down over the last 48 hours

**Comment by Alex7Kom** [comment]
Log what inventories (steamid, appid, contextid) you are loading when the error occurs.

**Comment by CodeLuca** [comment]
Sure, the problem is that it happens for every single trade, I have around 200 trades going through my bot a day, and they all get this error, ill grab an example for you now.

**Comment by CodeLuca** [comment]
@Alex7Kom 
Steamid: 76561198120532015
Appid: 730
Contextid: 2

**Comment by CodeLuca** [comment]
@Alex7Kom any ideas?

**Comment by Alex7Kom** [comment]
Would you please stop bumping threads? I'll reply as soon as I have any new info.

**Comment by Alex7Kom** [comment]
I can't reproduce the issue, and it occured to me that you use outdated version of `steam-tradeoffers`. Can you provide your full code and what versions of modules you use?

**Comment by CodeLuca** [comment]
it might be easier if I just add you to my repo, would that be okay?

**Comment by Alex7Kom** [comment]
Sure.

**Comment by CodeLuca** [comment]
@Alex7Kom beware. the code isnt very neat.

**Comment by Alex7Kom** [comment]
Oh, I see, so this error comes from Steam. Seems like a session issue: https://github.com/Alex7Kom/node-steam-tradeoffers/issues/45#issuecomment-64967515

**Comment by CodeLuca** [comment]
@Alex7Kom Im still getting this error all the time, even when steam doesnt seem to have any issues, any updates from your side?

**Comment by CodeLuca** [comment]
@Alex7Kom Was everything in that issue merged into the main repo? If not what should I do about it?

**Comment by CodeLuca** [comment]
@Alex7Kom im confused as to what to do about this

**Comment by Alex7Kom** [comment]
You need to refresh your session by obtaining cookies (using `webLogOn()` or whatever you use) and calling `setup()` again.

**Comment by CodeLuca** [comment]
@Alex7Kom ok

**Comment by CodeLuca** [comment]
@Alex7Kom Thanks for the help. Also 1 last question, a 503 error is steam screwing up right?
