### ISSUE TITLE
cant install module node-steam-client  get:   'doctormckay/steam-crypto' is not in the npm registry.

### ISSUE THREAD

**Issue by tambu22** [steam-forward/node-steam-forum#258]
i use : npm install steam-user

http://prntscr.com/bebq4h

'doctormckay/steam-crypto' is not in the npm registry.

**Comment by jwigley** [comment]
Did you try `npm i @doctormckay/steam-crypto` ?

https://www.npmjs.com/package/@doctormckay/steam-crypto
