### ISSUE TITLE
error 403 while accepting offer

### ISSUE THREAD

**Issue by dSyncerek** [steam-forward/node-steam-forum#26]
hi,
i created a bot that has to accept all offers with no items from me.
I'm using node-steam and node-steam-tradeoffers.
while bot try to accept offer returns error 403. i read that can be problem with my api key, but i regenerated it many times, deleted it or setup() generated key.
I'm sure accepting is performing after successful login.
I don't know what is cause of my problem.
thanks for help.

**Comment by jwigley** [comment]
Verify that you are passing the correct arguments to setup() (sessionID, webCookie, APIKey) and acceptOffer() (tradeOfferId). The parameter names are case sensitive.

setup() will not complain if you don't give it all the correct arguments.

**Comment by andrewda** [comment]
Also make sure that the `logOnResponse` event has been triggered before trying to accept any trade offers.
