### ISSUE TITLE
Count of items in trade? 

### ISSUE THREAD

**Issue by mworkg** [steam-forward/node-steam-forum#260]
How to get count of items in tradeoffer, before accept it?

**Comment by jwigley** [comment]
Count the number of items in the `items_to_receive` array.

https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#CEcon_TradeOffer

**Comment by mworkg** [comment]
can you send me nodejs code? i make but i get crash...

**Comment by andrewda** [comment]
`offer. items_to_receive.length` assuming you're using node-steam-tradeoffers.

**Comment by mworkg** [comment]
for example if i will write console.log(offer.items_to_receive.length) and will have 7 items in trade i will get 7 in console?

**Comment by mworkg** [comment]
yeah nice , thank you for help.
