### ISSUE TITLE
Empty info from trade

### ISSUE THREAD

**Issue by mworkg** [steam-forward/node-steam-forum#264]
I have  a part of script 
`var itemssend = '[' + result.map(function (item) { return ',{"market_hash_name":"' + item.market_hash_name + '", "classid":"' + item.classid + '", "assetid":"' + item.id + '", "rarity":"' + item.type + '", "price":""}'; }).join('\n');
`
`console.log(itemssend);`

Sometimes i get normal log.
But sometimes i get in log this `[` , log empty , but trade have items.

**Comment by andrewda** [comment]
First of all, why would you create your array like that?

```javascript
var itemssend = [];

result.forEach(function(item) {
    itemssend.push({
        "market_hash_name": item.market_hash_name,
        "classid": item.classid,
        "assetid": item.id,
        "rarity": item.type,
        "price": ""
    });
});
```

Either way, though, you're getting an empty `result` because Steam didn't send you the items. You should check to see if `result.length > 0`, and if it's not, then re-request the items from Steam.

**Comment by mworkg** [comment]
yea but how to re-request?

**Comment by andrewda** [comment]
What's your code? It will depend on how you request in the first place.

**Comment by mworkg** [comment]
Yea but i get empty assetid sometimes , after accept tradeoffer , assetid of items in my inventory.
