### ISSUE TITLE
Не отправляет трейд при его доступности

### ISSUE THREAD

**Issue by sweetru** [steam-forward/node-steam-forum#267]
У человека не прошел срок с нового устройства (7 дней), по идее его оффер доступен и ему можно отправить предмет, а он не может (это логично). Бот при отправке ему трейда выдает это: http://dl1.joxi.net/drive/2016/07/24/0004/0897/312193/93/a5819ba321.png Но ему можно отправить трейд, но пишет что холд.

Как решить эту проблему?
Спасибо.

**Comment by andrewda** [comment]
76561198055573465 and 76561198077593107 both have trade cooldowns from Escrow. Nothing you can do about that besides wait.

Also, please make issues in English.

**Comment by sweetru** [comment]
@andrewda that not bot, that users and i can trade for this users from my account, bot cant: reason bug.

**Comment by Alex7Kom** [comment]
Ask the person who wrote your bot to fix this. It should be a very simple change to the trade hold check to ignore a trade hold for the user who don't give away anything in the trade.

**Comment by andrewda** [comment]
@sweetru Sorry, guess Google Translate didn't translate your question well :P

As @Alex7Kom said, check with the person who wrote your bot. All you should have to do is something like this (obviously different depending on what trade offer module you're using):

```javascript
offer.getUserDetails(function(err, me, them) {
    if (them.escrowDays > 0) {
        offer.decline();
    } else {
        //do your offer checking here
    }
});
```

**Comment by sweetru** [comment]
@andrewda Man have 7 day hold with the access from new device, but his trade is available and it possible to send him an offer but he can't send trade himself. 
Bot said this when sending him the trade:
http://dl1.joxi.net/drive/2016/07/24/0004/0897/312193/93/a5819ba321.png
Bot can send him the trade, but steam says that trade will be hold.

offers.getHoldDuration({partnerAccountId: item.partnerAccountId, accessToken: item.accessToken}, function(err, response){ 
console.log(response); 
});

console.log write: {my: 0, their: 15}

**Comment by Alex7Kom** [comment]
The trade you describe will **NOT** be hold. If you only send items and don't ask for items in return, then hold duration of receiving side doesn't matter.

**Comment by sweetru** [comment]
Thanks all @andrewda @Alex7Kom
