### ISSUE TITLE
Changing the amount of items. What about the assetid?

### ISSUE THREAD

**Issue by Rellfy** [steam-forward/node-steam-forum#269]
Hey, I have been having a problem recently.

I realised that I cannot try to trade the same item twice or more in the same trade, or it will crash the bot node. I`m confused about what do I have to do, because each item has its own assetid, right? 

Well, I tried only changing the amount, and it didn't work. Then I tried to just to push another object with the other item with amount 1, but it doesn't work as well. As a last hope, I tried to set amount 2 (or any other depending of the deposit) and all the assetid strings as an array, but it didn't work as well.

Does anyone know what's going on, and what I'm supposed to do?

Thanks!

**Comment by andrewda** [comment]
Each item in your inventory has a unique assetid, even if they have the same name (i.e. two `AK47 | Redline (Factory New)`s will have different assetids). Therefore, you'll need to sort through your inventory and check the names of the items to get each item's unique assetid - again, they will all have different assetids.

Also, unless you're trading Spiral Knights currency, you'll **never** need to worry about the `amount` property.
