### ISSUE TITLE
Proxy, how to use it with node-steam-tradeoffers

### ISSUE THREAD

**Issue by MaxYari** [steam-forward/node-steam-forum#271]
Greetings, shady steam coders!

Question may be a bit silly, but can you give me an advise on subject?
I want to use proxies to make requests to steam community through `node-steamcommunity` and `node-steam-tradeoffers` in order to avoid requests per minute limit. 
I'm aware that both of them use `request`, i'm already monkey-patching it to implement some auto-retry functionality. I was attempting to use some free SOCKS5 proxies in request module, but I always get some connection errors and unable to do any requests.

I suppose it should be a pretty common thing to implement, would you be so kind to show me the right direction?

**Comment by Alex7Kom** [comment]
Try https://github.com/mattcg/socks5-http-client and https://github.com/mattcg/socks5-https-client.
AFAIK `request` doesn't work with SOCKS5 out of the box.

**Comment by MaxYari** [comment]
Should i actually use socks5 or is there other simpker options to proxy
bot's https requests?
09.10.2016 22:03 пользователь "Alexey Komarov" <notifications@github.com>
написал:
>
> Try https://github.com/mattcg/socks5-http-client and
https://github.com/mattcg/socks5-https-client.

**Comment by MaxYari** [comment]
I suppose i can actually attempt to monkeypatch sock5 requester in place of request module used in steam-community. But  for some reason i feel like there should be a simpler, more elegant solution. Again it looks like such a common hurdle to overcome if you are developing steam bots, so what is usually used to proxy them?

**Comment by Alex7Kom** [comment]
You can use `socks5-http(s)-client` with `request` easily, just pass it with default settings as a proxy agent to `request`.

**Comment by MaxYari** [comment]
Got it, will try, thanks for advise and for a great projects, Alex!
