### ISSUE TITLE
'ETIMEDOUT' while sending tradeoffer. 

### ISSUE THREAD

**Issue by hell00world** [steam-forward/node-steam-forum#274]
Hello, i have got that error, while sending trade. Sometimes it's sends a tradeoffer, but usually no.

```
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT', connect: false }
Error: ETIMEDOUT
    at null._onTimeout (node_modules/steam-tradeoffers/node_modules/request/request.js:759:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

How to prevent that? Where can I change ETIMEDOUT limit? Better way to prevent that? (sometimes trades are sended, but steam-tradeoffers says Errror: ETIMEDOUT).

**Comment by andrewda** [comment]
`ETIMEDOUT` means you are not connected to the Steam servers. Make sure that

1. You are connected to the internet.
2. Your connection to the Steam servers are reliable.

The issue could also be that Steam is down – wait a while and see if it starts to work again.

**Comment by hell00world** [comment]
Thanks for the anwser andrewda.
1. I am sure I am connected to the internet, because I am executing script from dedicated web servers.

> wait a while and see if it starts to work again.
Yes, next requests working usually fine.

**Comment by hell00world** [comment]
So... What can I try to do?

**Comment by hell00world** [comment]
I just need to be sure trade offer isn't sent. Because sometimes when "ETIMEDOUT" Steam sends tradeoffer.

**Comment by Kuba77** [comment]
I suggest using getOffers() to confirm when that happens.

**Comment by hell00world** [comment]
Ok, dzięki ;)
A dać na to jakiś kawałek czasu, w sensie żeby nie było tak żeby nie zwrócił false a oferta została wysłana?

**Comment by Kuba77** [comment]
Nie jestem pewien, wydaje mi się, że oferta zawsze może pojawić się z bardzo dużym opóźnieniem. Dobrym rozwiązaniem byłoby dopisanie do opisu oferty losowo wygenerowanego kodu, a potem sprawdzanie cyklicznie, na przykład co pięć sekund wszystkie wysłane oferty i aktualizowałem ich statusu na podstawie tego kodu, zamiast ich id zwróconego przez Steam.

Not sure, iirc some offers might appear with a very big delay. A good solution would be to append a randomly generated string to the offer description, and to check status of all the sent offers periodically in a loop then in order to update their status based on that string, rather than id as returned (or not) by Steam.

**Comment by hell00world** [comment]
Hmm, a tak szybciej to moznaby sprawdzić zwrócony error, i jezeli to bedzie ETIMEDOUT to po pół minuty/minucie sprawdzić getOffer na podstawie... No wlasnie, czego? 
Chyba ze sprawdzić getOffers() na podstawie losowego kodu dołączanego do opisu oferty... ale jak powiązać to co zwróci getOffers() z tym losowym kodem?

**Comment by hell00world** [comment]
A nie da się prościej? Chodzi tylko o to żeby w przypadku wystąpienia tego błędu nie mogło wysłać użytkownikowi oferty wymiany.

**Comment by Alex7Kom** [comment]
@hell00world This is an English forum, so please speak English.

**Comment by hell00world** [comment]
Ok, sorry.

**Comment by hell00world** [comment]
Hmmm, maybe, is it possible to increase ETIMEDOUT time (limit)?

**Comment by Alex7Kom** [comment]
It is possible and it is written in the docs https://github.com/Alex7Kom/node-steam-tradeoffers#setupoptions

**Comment by hell00world** [comment]
Haha, I didn't saw that! Sorry.  I will increase that and I will wait for results. 
Thank you!

**Comment by hell00world** [comment]
Hello.
I saw - sometimes Steam SENDS tradeoffer, while steam-tradeoffers is processing sendOffer(), but after 30 seconds it throws: ETIMEDOUT

**Comment by hell00world** [comment]
Changing it to 60 seconds - no results. Still getting ETIMEDOUT. Now I changed it to the 20 seconds and I am waiting for results.

**Comment by hell00world** [comment]
Heyyy guys!
I figured it out.
Just need to add `loadPartnerInventory()` before sending a tradeoffer to prevent sending tradeoffer with ETIMEDOUT.

**Comment by andrewda** [comment]
That doesn't seem right... Something else is probably going on there.

**Comment by BlackOnix** [comment]
I also have this problem ..
If I load the inventory - I get error Invalid Response or etimedout
If I load a list offers - I get etimedout

Tried to connect a proxy, it does not help
The server is located in France
Proxy - Russia

**Comment by hell00world** [comment]
My server is also located in France.
