### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by tonttu16** [steam-forward/node-steam-forum#278]
My bot worked perfectly but then suddenly it throws error `cannot read property 'get' of undefined`. 
I logged in and out with my bot many times could it be the problem?

    offers.getOffers({
        get_received_offers: 1,
        active_only: 1,
        time_historical_cutoff: Math.round(Date.now() / 1000)
    }, function(err, body) {

    if(err) {
        console.log(err);
    }

    if(body.response.trade_offers_received) {

        body.response.trade_offers_received.forEach(function(offer) {

	        console.log("Trade offer from " + offer.accountid_other);

	        if(offer.items_to_give) {

	            offers.declineOffer({
	                tradeOfferId: offer.tradeOfferId
	            }, function(err, results) {
		        console.log("Offer: " + offer.tradeofferid + " Declined");
	            })

            } else if(offer.items_to_receive) {

	            offers.acceptOffer({
	                tradeOfferId: offer.tradeOfferId,
		        partnerSteamId: offer.accountid_other
	            }, function(err, results) {
	                console.log("Offer: " + offer.tradeOfferId + ", from: " + offer.accountid_other +" accepted");
	            })

	        }

        })

    }

    })

**Comment by andrewda** [comment]
Post the entire stack trace, please. The issue you mentioned is not in the code above.

**Comment by tonttu16** [comment]
The error comes when I launch my bot and it has active trade offers already. So before I launch my bot I need to cancel all received trade offers from bot otherwise I get that error.
