### ISSUE TITLE
using proxies

### ISSUE THREAD

**Issue by Nexetion** [steam-forward/node-steam-forum#281]
I need some help with implementing proxies into my bot system, if anyone can give me any guidance it would be appreciated I could also pay anyone that helps me.

**Comment by unusual917** [comment]
Did anyone get to help you? Can you refer me since I am looking for someone who can help me with something like this too.

**Comment by gokarter24** [comment]
No one has helped me :/

**Comment by Mozorianer** [comment]
`offers.setup({
        sessionID: sessionID,
        webCookie: cookies,
        APIKey: key,
        requestOptions: {
            localAddress: ipadresshere
        }
    });`

replace ipadresshere with your ip and its using it! :)
