### ISSUE TITLE
GetOffers ETIMEDOUT

### ISSUE THREAD

**Issue by BlackOnix** [steam-forward/node-steam-forum#283]
Hello, Often there was an error in getting offers
{ [Error: connect ETIMEDOUT 23.202.128.162:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '23.202.128.162',
  port: 443 }

I tried to use a private proxy, but it did not help
What can be done about this?

**Comment by tambu22** [comment]
#274 maybe helps you, i have the same issue changed the timeout to 140000 but the i continue getting the error on getOffers
