### ISSUE TITLE
Hello,steambot does not send the winnings

### ISSUE THREAD

**Issue by dmitriy28** [steam-forward/node-steam-forum#290]
What should I do?

**Comment by andrewda** [comment]
We have no idea what you programmed. There could be infinite issues causing it not to work without knowing your code or a description of your error.

**Comment by dmitriy28** [comment]
[steambot.js.zip](https://github.com/steam-forward/node-steam-forum/files/1066041/steambot.js.zip)

**Comment by dmitriy28** [comment]
In bot's account i need accept sending 
But  normaly,bot must accept this

**Comment by andrewda** [comment]
Ah, you're going to need to use node-steam-community. There's a method in there for accepting trades with 2FA.

**Comment by dmitriy28** [comment]
I know.
I have installed.
But the winnings only heading of when I turn on bot

**Comment by dmitriy28** [comment]
But when he works,he does not send
Only when I turn on him
