### ISSUE TITLE
Did I make something wrong?

### ISSUE THREAD

**Issue by AndrewRAN** [steam-forward/node-steam-forum#293]
Here's my code:

`var Steam = require('steam');
var SteamWebLogOn = require('steam-weblogon');
var SteamTotp = require('steam-totp');
var getSteamAPIKey = require('steam-web-api-key');
var SteamTradeOffers = require('steam-tradeoffers');

var logOnOptions = {
  account_name: 'mylogin',
  password: 'mypassword',
  twoFactorCode: SteamTotp.generateAuthCode('mysharedsecret')
};

var steamClient = new Steam.SteamClient();
var steamUser = new Steam.SteamUser(steamClient);
var steamFriends = new Steam.SteamFriends(steamClient);
var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);
var offers = new SteamTradeOffers();

steamClient.connect();
steamClient.on('connected', function() {
  steamUser.logOn(logOnOptions);
});

steamClient.on('logOnResponse', function(logonResp) {
  if (logonResp.eresult === Steam.EResult.OK) {
    console.log('Logged in!');
    steamFriends.setPersonaState(Steam.EPersonaState.Online);
    client.gamesPlayed("Cubson trade bot [No offers pending]");
    steamWebLogOn.webLogOn(function(sessionID, newCookie) {
      getSteamAPIKey({
        sessionID: sessionID,
        webCookie: newCookie
      }, function(err, APIKey) {
        offers.setup({
          sessionID: sessionID,
          webCookie: newCookie,
          APIKey: APIKey
        });
      });
    });
  }

 loadMyInventory(730, 2);
});`

When starting there is an error appearing:
![screenshot_2](https://user-images.githubusercontent.com/23475741/27077059-56018d12-5048-11e7-9830-ac92227dcaec.png)

**Comment by andrewda** [comment]
https://github.com/seishun/node-steam/wiki/Protobufs#cmsgclientlogon

Use `two_factor_code` for node-steam. `twoFactorCode` is what node-steam-user uses.

**Comment by AndrewRAN** [comment]
Are you talking about this thing?
`var logOnOptions = {
account_name: 'mylogin',
password: 'mypassword',
twoFactorCode: SteamTotp.generateAuthCode('mysharedsecret')
};`

**Comment by andrewda** [comment]
I believe you're calling `offers.loadMyInventory()` _before_ you've successfully passed the necessary cookies to node-steam-tradeoffers. JavaScript code executes asynchronously, so if there's an action that requires a callback (in this case `steamWebLogOn.webLogOn()` and `getSteamAPIKey()`, other code will execute before the callback is called, even if the code is below. Move `offers.loadMyInventory(730, 2);` inside of the `getSteamAPIKey()` callback, immediately after your `offers.setup()` call. It should look something like this:

```javascript
steamWebLogOn.webLogOn(function(sessionID, newCookie) {
    getSteamAPIKey({
        sessionID: sessionID,
        webCookie: newCookie
    }, function(err, APIKey) {
        offers.setup({
            sessionID: sessionID,
            webCookie: newCookie,
            APIKey: APIKey
        });

        offers.loadMyInventory(730, 2);
    });
});
```

Note that your `offers.loadMyInventory()` call isn't going to do anything without a callback.

PS: in the future, use three backticks (```) to format your code correctly :+1:

**Comment by AndrewRAN** [comment]
I already use backticks btw. Thank you very much about telling about asynchronity in JS. I'm a big noob in it and you help me a lot to stop being him.

**Comment by AndrewRAN** [comment]
> Note that your offers.loadMyInventory() call isn't going to do anything without a callback.
Could you provide an example?

**Comment by shaunidiot** [comment]
You need something like
```
offers.loadMyInventory({
    appId: 730,
    contextId: 2
  }, function(err, items) {
   if (err) {
     return console.log(err);
   }
    console.log(JSON.stringify(items, null, 2));
});
```

**Comment by AndrewRAN** [comment]
Thank you.
