### ISSUE TITLE
[steam-tradeoffers] Sentry files invalid upon updating to 2.0.0

### ISSUE THREAD

**Issue by clabby** [steam-forward/node-steam-forum#30]
After the new update (2.0.0), the sentry files for my bots have become invalid, and steam requests for a steam guard code upon log-in. Has anyone come up with a way to convert sentry files, or do I just have to wait a week for my bots to be un-trade-banned?

Thanks in advance.

**Comment by Alex7Kom** [comment]
They are not invalid, just the method of saving sentry files in examples of trade offers is changed. It is now recommended to store all bytes of sentry not just SHA1.

You can supply old sentry files by changing the line:
```js
logOnOptions['sha_sentryfile'] = getSHA1(fs.readFileSync('sentry'));
```

to:

```js
  logOnOptions['sha_sentryfile'] = fs.readFileSync('sentry');
```

**Comment by clabby** [comment]
Ah, great! Thanks for the fast response. :+1:
