### ISSUE TITLE
problems with node-steam-trade

### ISSUE THREAD

**Issue by escept** [steam-forward/node-steam-forum#301]
Modules: node-steam-trade
Basically what i want is to add items to trade what contains a string in the name. I couldn't do it since the past 5 hours. Can anyone help?

**Comment by escept** [comment]
Nvm i fixed it myself. This forum is pretty dead..

**Comment by andrewda** [comment]
In the future, if you want someone to help, you'll need to provide more details. Post your code. Post what you've already tried.
