### ISSUE TITLE
getoffers problem

### ISSUE THREAD

**Issue by dvdx95** [steam-forward/node-steam-forum#302]
hi, im using getoffers in my bot.
I did never had that problem before, it was started yesterday.
So i do request 

offers.getOffers({
			get_received_offers: 1,
			active_only: 1,
			get_sent_offers: 0,
			get_descriptions: 1,
			language: "en_us"
		}, function(error, body) {

then script is starting asking api 5-6 times a second about the same and i always receive in body

{ response: { trade_offers_received: [ [Object]] } }
{ response: { trade_offers_received: [ [Object]] } }
{ response: { trade_offers_received: [ [Object]] } }
{ response: { trade_offers_received: [ [Object]] } }
{ response: { trade_offers_received: [ [Object]] } }
{ response: { trade_offers_received: [ [Object]] } }
{ response: { trade_offers_received: [ [Object]] } }
{ response: { trade_offers_received: [ [Object]] } }
 and that is going forever untill i dont stop script, it happend also to makeOffer 

Do you guys have any idea why that is happend?

**Comment by alex7kom** [comment]
Make sure your script doesn't call `getOffers` and `makeOffer` inside some loop.

**Comment by dvdx95** [comment]
no it doesn't call it in loop.

That was happend yesterday, i did not change anything in this script 
the code is similar to that from examples

there is no loop here, i have no idea what was happend, i also tried to run script in other server and it's the same problem.
function checkoffers(){
		offers.getOffers({
			get_received_offers: 1,
			active_only: 1,
			get_sent_offers: 0,
			get_descriptions: 1,
			language: "en_us"
		}, 
		function(error, body) {
			console.log(body);
			if(error !== null) {
			setTimeout(checkoffers,5000);
			return;
			} // and the rest of the script

i receive in console.log(body);
{ response: { trade_offers_received: [ [Object]] } } and it doing loop i dont know why.
i checked also console.log(error) and it's always null

Do you have any idea?

**Comment by dvdx95** [comment]
// i checked my bot account and (only)market is blocked for selling/buying , may it be the problem??

**Comment by alex7kom** [comment]
What is calling `checkoffers()` initially?

**Comment by dvdx95** [comment]
steam.on('tradeOffers', checkoffers);
setInterval(checkoffers,600000);
that what i have in file

**Comment by dvdx95** [comment]
thats is my console.log

mysql connected!
false
false
connected
connected
encrypt request
encrypt request
handshake complete
handshake complete
Logged in!
webSessionID ok
webLogOn ok
Pending confirmations: 0
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }
{ response: 
   { trade_offers_received: [ [Object], [Object], [Object], [Object] ],
     descriptions: [ [Object] ] } }

**Comment by dvdx95** [comment]
and it's gaoing the same forever  { response:
{ trade_offers_received: [ [Object], [Object], [Object], [Object] ],
descriptions: [ [Object] ] } }

**Comment by dvdx95** [comment]
Do you have any idea what it can be?

**Comment by dvdx95** [comment]
i still can not find the issue of offers.makeOffer and offers.checkOffers
is calling steam api all the time when it run on script.
for example with offers.loadMyInventory there is not any problem, the call is only 1

**Comment by dvdx95** [comment]
may it be the problem with session?
Alex i hope you will be able to give me any clue.

**Comment by dvdx95** [comment]
Hi Alex,
I run this script for very long time and i never had that problem before.

When i call offers.makeOffer or offers.checkOffers my script is just
starting ask steam api several time a second(and it not stop).
I normally receive response, for examples bot is normally accepting trade
but he still asking api for checkOffers... and i dont know why.
It never happend before.
Do you have any ide what may be the problem?
meybe callback or sessionid, i have checked my steamapi and i normally
receive request.
if i do normal request in my bot the it's called only 1 time, but when i
use offers.checkOffers then is happend something wrong...

If you are able to help me i will appreciate it.

2017-11-17 11:52 GMT+01:00 Alexey Komarov <notifications@github.com>:

**Comment by dvdx95** [comment]
After my conversation witch Alex, we came to the solution.

Problem is on steam.on('tradeOffers',

somehow this going into loop, the solution that we found is really easy

var offer = true;
steam.on('tradeOffers', function(number) {
  if (number > 0 && offer== true) {
offer = false;
    console.log('from tradeOffers!'); checkoffers()
setTimeout(function(){offer = true},4000);
  }
  offer;
});

I hope that will help someone with the same problem.

I will be also trying to find out why steam.on('tradeOffers', going into
infinite loop

Thanks


2017-11-17 14:30 GMT+01:00 Super Shot <grzybowskiprzemek19@gmail.com>:
