### ISSUE TITLE
Can't add people that were added when the bot was offline

### ISSUE THREAD

**Issue by Nikita2150** [steam-forward/node-steam-forum#306]
So, I've decided to create a steam bot but the problem is that I can't add friends that were added when the bot was offline.
Here's my code for that:
```
client.on('friendsList', function() {
    for (var sid in client.myFriends);
        var relationship = client.myFriends[sid]
        if (relationship == SteamUser.EFriendRelationship.RequestRecipient) {
        console.log("(offline) We recieved a friend request from "+sid);
        client.addFriend(sid, function (err, name) {
            if (err) {
                console.log(err);
                return;
            }
            console.log("(offline) Accepted user with the name of "+name)
        })
    }
})
```
Actually I've gotten this code from this youtube video:
https://www.youtube.com/watch?v=U7UfvHwoptM

I'm using the same code, for him it works.

**Comment by alex7kom** [comment]
This code has a bug, the `for ... in` statement doesn't have a body, instead it ends with `;`, so it will loop over the friend list doing nothing and the following code will be executed only on the last item, because it will remain in `sid` variable.

The correct code:

```js
client.on("friendsList", function () {
  for (var sid in client.myFriends) {
    var relationship = client.myFriends[sid];
    if (relationship == SteamUser.EFriendRelationship.RequestRecipient) {
      console.log("(offline) We recieved a friend request from " + sid);
      client.addFriend(sid, function (err, name) {
        if (err) {
          console.log(err);
          return;
        }
        console.log("(offline) Accepted user with the name of " + name);
      });
    }
  }
});
```
(I've also reformatted the code, so the coding style is somewhat consistent.)

**Comment by Nikita2150** [comment]
Thank you for the fast answer, actually I've figured out the problem by myself just rn and saw your answer.
Thank you again!
