### ISSUE TITLE
Set expire time on a trade offer

### ISSUE THREAD

**Issue by NadirRed** [steam-forward/node-steam-forum#308]
##### Problem description:
How can i set the expire time to 30minutes when i send a trade offer

##### I use the following libraries:
steam-tradeoffers

**Comment by andrewda** [comment]
There's now way to do this natively with Steam. Instead you should save the trade and its expiration time somewhere (like a database, JSON file, in-memory) and poll it ocassionally. When a trade reaches that time, [cancel it](https://github.com/Alex7Kom/node-steam-tradeoffers#cancelofferoptions-callback).
