### ISSUE TITLE
Reuse Cookies and SessionID (node-steam-tradeoffers)

### ISSUE THREAD

**Issue by inferno001** [steam-forward/node-steam-forum#31]
Hey,

i am trying to reuse cookies and sessionid I received from calling "webLogOn".

In a JS file I login into steam and saving the received cookies and sessionid.
```
steamClient.on('logOnResponse', function (logonResp) {
    if (logonResp.eresult == Steam.EResult.OK) {
        steamWebLogOn.webLogOn(function (sessionID, newCookie) {
            getSteamAPIKey({
                sessionID: sessionID,
                webCookie: newCookie
            }, function (err, APIKey) {
                saveToFile(sessionID, newCookie);
            });
        })
    }
});
```
In another file I want to reuse them in "offers.setup({})", but it is always returning 401 errors.
```
offers.setup({
    sessionID: readFromFile().sessionID,
    webCookie: readFromFile().cookies,
    APIKey: 'XXX'
}, function (err) {
    var offerOptions = {}
    offers.makeOffer(offerOptions, function (err) {
        // err = 401
    });
});
```

If I call webLogOn right before offers.setup the code is working. Could someone help me?

**Comment by kh304** [comment]
WE NEED THIS FOR REAL

**Comment by kh304** [comment]
maybe the code will work but no actual ACCEPTANCE available or realized

**Comment by kh304** [comment]
so i mean steam  shorten the route for yea

**Comment by dolanmiu** [comment]
I currently am saving the  sessionID, webCookie and API key in variables, and it seems to work fine! Doesn't need to "save to file". That's a bit overkill in my opinion.
