### ISSUE TITLE
How to get AssetID after trade?

### ISSUE THREAD

**Issue by MaTyyyJ** [steam-forward/node-steam-forum#32]
Hello.

I have, a problem. I don't know how to get a AssetID of my items after acceptOffer()
I can only get AssetID on trade, but i don't know how to get this id after trade :(
I want to put this id to database and use it to send offers.

**Comment by andrewda** [comment]
Can't you save the AssetID immediately when you receive the trade, and then use it for what you need after you accept it? Something like this?

    var assetids = [];
    offer.items_to_receive.forEach(function(current, index, array) {
        assetids.push(current.assetid);
    });
    offers.acceptOffer({tradeOfferId: offer.tradeofferid}); // accept the trade

Here, `assetids` is an array containing all the AssetIDs of the items that were sent to you. Then you can do what you want with the array of AssetIDs.

**Comment by scholtzm** [comment]
@andrewda Asset IDs will change right after you accept the trade.

**Comment by BenWoodford** [comment]
offers.getItems(offerObject.tradeofferid) will get the _new_ item IDs. Assuming offerObject is your offer from getOffers() or getOffer(). Take note tradeofferid and tradeid _are not the same_/

**Comment by k1b0rg** [comment]
After accept trade, I get assetid of items on this page steamcommunity.com/trade/XXXXXXXXXXXXXXX/receipt
after a while, assetid changes.
how to define a new one?

**Comment by BenWoodford** [comment]
Don't rely on it long term, I'm finding items can go into a trade, be cancelled and change asset ID.

**Comment by Dwynr** [comment]
I'm also still looking for a solution for this.
I need to get the assetid's after my bot accepts the trade in case there are duplicate items.

**Comment by feedarz** [comment]
@scholtzm it actually wont. It takes some time for item to leave inventory. How can you be 100% that you got UPDATED assetid?

For me i was using getOffers to get states, then i check if state == 3, and then i tried to obtain assetid. Unfortunatly it gives me old one.

**Comment by scholtzm** [comment]
> then i tried to obtain assetid

how?

**Comment by feedarz** [comment]
@scholtzm getItems.

**Comment by feedarz** [comment]
@scholtzm still no solution here?

**Comment by scholtzm** [comment]
I've never had this issue. Post in /r/SteamBot, perhaps someone has the same problem.

**Comment by feedarz** [comment]
@scholtzm Maybe you are missunderstood this topic as a whole. Maybe you noticed, when you accept big or huge tradeoffers state is changed, but items are still in your inventory? Thats called item draft, so if trade is huge steam is transfering items between accounts slowly and that is the case of the problem. AssetIDs only changing when transfering, not when tradeoffer has 3 state.

So how to verify thats items are transfered?

**Comment by timmy78** [comment]
Same question :/

**Comment by Alex7Kom** [comment]
https://github.com/steam-forward/node-steam-forum/issues/80#issuecomment-138760706
