### ISSUE TITLE
 body.response.descriptions undefined 

### ISSUE THREAD

**Issue by GuidoRumi** [steam-forward/node-steam-forum#35]
I'm trying to migrate from the old storehouse example to the new one, as the first wasn't accepting offers.

I was using body.response.descriptions on steamUser.on('tradeOffers', function(number) { ... } ) to retrieve hash_names. On last version, descriptions is not longer part of body.response.

Is this intended? Is there an other way to get descriptions?

Thanks in advance

**Comment by Alex7Kom** [comment]
There wasn't any change in `steam-tradeoffers` in that regard. Descriptions are not returned by Web API by default, you need add `get_descriptions: 1` param to `.getOffers()` call.

**Comment by GuidoRumi** [comment]
Thanks!
