### ISSUE TITLE
SteamClient._disconnected

### ISSUE THREAD

**Issue by Sttrelllok** [steam-forward/node-steam-forum#39]
**Help needed!**

*Code:*

`root@vm12444:~/bot# node ~/bot/hope.js`
       `events.js:85`
      `throw er; // Unhandled 'error' event`
            `^`
    `Error: Disconnected`
                   `at SteamClient._disconnected (/root/bot/node_modules/steam/lib/steam_client.js:196:24)`
                    `at Connection.emit (events.js:107:17)`
                     `at TCP.close (net.js:485:12)`

*please*

**Comment by andrewda** [comment]
Could you add your code, please? Looking at this, I assume that you did not enter your auth_code or your auth_code / sentry file is incorrect.

**Comment by Sttrelllok** [comment]
I can't receive auth code, because node can't connect to servers...

**Comment by andrewda** [comment]
When you run the bot without an `auth_code` specified, the error you showed above will be output to the console, and a code should be emailed to you. Every time you start the bot, you will need to enter a new `auth_code` that gets emailed to you. If you want to avoid having to constantly enter a new `auth_code`, specify the sentry file.

**Comment by Sttrelllok** [comment]
var logOnOptions = {
account_name: 'Mylogin',
password: 'My Password'
};
var authCode = 'GHSJ1'; // code received by email

aaand

error!


events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Disconnected
    at SteamClient._disconnected (/root/bot/node_modules/steam/lib/steam_client.js:196:24)
    at Connection.emit (events.js:107:17)
    at TCP.close (net.js:485:12)

**Comment by andrewda** [comment]
Remove the value of `authCode` and run the bot again. Then check your email and there should be a new authcode. Enter that, and you should be good.

**Comment by Sttrelllok** [comment]
No, you didn't understend. Node can't connect to steam! She do not care what the login data I have.

**Comment by scholtzm** [comment]
Well, you should handle the `error` event. The stack trace tells you this.

**Comment by bercik809** [comment]
I had the same problem and i've created new steam guard code and it worked.

**Comment by PokeRwOw** [comment]
Same problem for me, can't include prompt to enter the code steam guard

**Comment by DDSZ1337** [comment]
Well, I have the same problem. Guard key works only for first launch. Then, if I restart it, it will throw this error and I will need to get a new key... Any thoughts? Im using demo donation bot :)

**Comment by andrewda** [comment]
You gotta setup the sentry file, @DDSZ1337. You can find out how in the docs.

**Comment by DDSZ1337** [comment]
Sentry is being created, @andrewda.
I am talking about this example: https://gist.github.com/Alex7Kom/d764ef2925060c4e7c27#file-donation_bot-js

**Comment by Alex7Kom** [comment]
@DDSZ1337 Does it create `sentry` file?

**Comment by DDSZ1337** [comment]
@Alex7Kom, yes, but it looks like it is not being used if I remove authKey after successful authorisation.

**Comment by Alex7Kom** [comment]
@DDSZ1337 Please, would you create a new issue, so we can continue? I feel this is offtopic here.

**Comment by lparamonov** [comment]
@Sttrelllok have you found a solutiob?

**Comment by andrewda** [comment]
@lparamonov read what @ghost wrote:

> I had the same problem and i've created new steam guard code and it worked.

However, this is completely irrelevant if you're using mobile codes...
