### ISSUE TITLE
"Error: There was an error sending your trade offer. Please try again later. (8)"

### ISSUE THREAD

**Issue by BenWoodford** [steam-forward/node-steam-forum#4]
This is using node-steam-tradeoffers for reference.

I've been trying to find some information on this one, but can't find anything anywhere.

I recently refactored most of my bot code into a module to make it tidier, but in the process this one is starting to pop up. I'm printing the offerOptions value prior to calling makeOffer and this is what it shows (censored):

```{"partnerSteamId":"0000000000000","accessToken":"abcdefg","message":"foobar","itemsFromMe":[{"appId":730,"contextid":2,"amount":1,"assetid":2568089830}]}```

Has anyone come across anything like this? Everything is definitely logging in just fine, I'm using the kew promise library so my bot can't even start trading until it logs into both Steam and the Web interface (which both succeed). To clarify, it gets past the loggedOn event, webSessionID event, and no error is returned using offers.setup()

**Comment by Alex7Kom** [comment]
`itemsFromThem` is required even if it is an empty array.

**Comment by BenWoodford** [comment]
No dice unfortunately. I don't believe I needed it on my old code either, I only ever filled one of them and never set the other.

**Comment by scholtzm** [comment]
Have you tried providing the assetid as a string?

`"assetid":"2568089830"`

**Comment by AardvarkMike** [comment]
I believe I had the same problem.

It was when I was trying to use assetid from the tradeoffer - the solution was to use the id from getItems() / web api inventory.

**Comment by BenWoodford** [comment]
@scholtzm It's definitely tradeable, and regarding the asset ID being a string: Never had any issue with it being a numeric before, but I'll check it just in case.

@AardvarkMike That is where I'm getting the IDs from, this is just refactored code drawing from the same database and using the same data types. :/ The only single difference is the account in use, but it trades fine when done manually via a browser.

**Comment by BenWoodford** [comment]
toString()'d the assetid and still not working sadly.

**Comment by BenWoodford** [comment]
If it provides any insight, the HTTP code the request returns is 500, so considering Steam (usually) provides a relevant HTTP code I presume we can rule out authentication issues?

**Comment by scholtzm** [comment]
The only thing I can think of right now is to compare the HTTP request done by browser (which I assume works) with the HTTP request done by node. There must be a difference somewhere. (?)

**Comment by BenWoodford** [comment]
I was just playing with that actually, both via my account and the bot account (which has a trade ban on my browser for being a new device). The only difference I can see is that there's an empty captcha field in the form data, and version is 6 on the bot's account whereas it's 2 in the library (and 2 on my own account, so hell if I know how they decide that).

The cookie has a rather larger abundance of stuff in it, stuff like strTradeLastInventoryContext=730_2, bCompletedTradeOfferTutorial=true, etc. But I wouldn't have thought that would cause a problem as it never has before.

**Comment by BenWoodford** [comment]
I just tried with another account made for bot purposes, and it's throwing up the same error.

Perhaps it's something to do with newer accounts? Something they do differently (the version disparity between my own account's form data and the newer bot account's form data makes me wonder).

Just throwing ideas around really, I'm at a loss.

**Comment by jhartzell** [comment]
@BenWoodford I'll be battling this one out with ya man, I am now having this issue as well, will be trying a few of my several year old accounts as well as all my newer ones as they are all registered to the bots device. I'll keep you updated if I find anything!

**Comment by jhartzell** [comment]
```javascript
TradeOffers.makeOffer({
                    partnerSteamId: '76561197997278394',
                    itemsFromMe: [{
                        appId: 730,
                        contextId: 2,
                        amount: 1,
                        assetid: item.id
                    }],
                    itemsFromThem: [],
                    message: 'This is a test'
                }, function(err, response) {
                	console.log(response);
                    if (err) {
                        throw err;
                    }
                    console.log(response);
                });
````

**Comment by BenWoodford** [comment]
Always nice to not be alone in a problem :)

I've just checked my code and I have appId instead of appid. I'll have a look at this when I'm on my laptop again, if this is the cause I'm going to be kicking myself for days.

**Comment by scholtzm** [comment]
Yep, looks like you finally found the culprit. :+1: 

https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd#L11

**Comment by jhartzell** [comment]
:+1:

**Comment by BenWoodford** [comment]
@jhartzell I could hug you right now.

PAY ATTENTION TO YOUR CASING PEOPLE.

**Comment by jhartzell** [comment]
Glad I could help!

**Comment by Netifriik** [comment]
I'm having the same problem. All properties seem to be lowercase but I'm still getting (8).

``
itemFromMyInventory[num] = {
    appid: 730,
    contextid: '2',
    amount: parseInt(items[x].amount), // doesn't matter if int or string, still fails
    assetid: items[x].id
}
``
``
offers.makeOffer ({
    partnerSteamId: row[i].userid,
    itemsFromMe: itemFromMyInventory,
    accessToken: row[i].token,
    itemsFromThem: [],
    message: 'Have fun'
``

Any help appreciated.

**Comment by scholtzm** [comment]
Couple things:

1. For CS:GO items, `amount` must be always `1`.
2. Make sure the `assetid` is typeof `string`.
3. Make `contextid` a number.
4. `itemsFromThem` doesn't have to be there if it's an empty array.

**Comment by Netifriik** [comment]
``
{ appid: 730, contextid: 2, amount: 1, assetid: '3495258771' } 
``

    offers.makeOffer ({
        partnerSteamId: row[i].userid,
	itemsFromMe: itemFromMyInventory,
	accessToken: row[i].token
    }

Still getting the same error

**Comment by scholtzm** [comment]
Try to send a single item with hardcoded values and go from there.

**Comment by Netifriik** [comment]
Does accessToken change over time? I'm trying to use 3-4h old access tokens.

**Comment by scholtzm** [comment]
It never changes unless reset manually.

**Comment by andrewda** [comment]
itemFromMyInventory[0] = {
        appid: 730,
        contextid: 2,
        amount: 1,
        assetid: '3479736434'
    };
    
    offers.makeOffer ({
        partnerSteamId: '76561198092490523',
        itemsFromMe: itemFromMyInventory,
        accessToken: 'HuEE9Mk1',
        itemsFromThem: [],
        message: 'Have fun'
    }, function(err, response) {
        if (err) throw err;
    });

The above code works fine for me, however so does this code:

    itemFromMyInventory[0] = {
        'appid': '730',
        'contextid': '2',
        'amount': '1',
        'assetid': '3479736434'
    };
    
    
    offers.makeOffer({
        'partnerSteamId': '76561198092490523',
        'itemsFromMe': itemFromMyInventory,
        'accessToken': 'HuEE9Mk1',
        'itemsFromThem': [],
        'message': 'Have fun'
    }, function(err, response) {
        if (err) throw err;
    });

If neither of those work for you, a few things to tack onto what @scholtzm said might be:

-  Verify that the `accessToken` is only the part after `&token=` in the URL (though this should cause error 15 instead of 8)

- Check to make sure `partnerSteamId` is a string (again, this should cause another error, but it can't hurt to check)

**Comment by JustPlaysDE** [comment]
I have the same problem....
If i replace appId with appid or contextId with contextid it  is spamming: "web authentication 403, retrying".
Sometimes the trade offer will be sent (!!), sometimes not with the error: "Error: There was an error sending your trade offer.  Please try again later. (8)".
Any idea?

**Comment by scholtzm** [comment]
> it is spamming: "web authentication 403, retrying"

That's your code spamming, not the library.

And error 8 means "invalid parameters".
