### ISSUE TITLE
GetOffers response problem.

### ISSUE THREAD

**Issue by bercik809** [steam-forward/node-steam-forum#40]
Hello,

I have problem, i don't know why, but if I want to receive my offers from my account on steam i have error " 'response' of undefined." What can I do? 

I'm talking about this:
'body.response.trade_offers_received.forEach'

**Comment by bercik809** [comment]
I think it's problem with 'time_historical_cutoff'.

**Comment by andrewda** [comment]
Could we please see your code so we can try to help?

**Comment by bercik809** [comment]
steamUser.on('tradeOffers', function(){
         offers.getOffers({
            get_received_offers: 1,
            active_only: 1,
            time_historical_cutoff: Math.round(Date.now() / 1000)
        },function(error, body){
            body.response.trade_offers_received.forEach(function(offer){


And i have that error in last line ' body.response.trade_offers_received.forEach'.

If my bot have to accept a couple offers sometimes i have that error. Then if i my bot have to accept one offer i have that error. I don't know what i have to do?

**Comment by scholtzm** [comment]
Why are you blindlessly skipping the `error` argument in your callback function?

**Comment by bercik809** [comment]
Sorry for format of my code.  Okay i've added  <code>error</code> and i have <code>TypeError: Cannot read property 'forEach' of undefined.</code>

**Comment by bercik809** [comment]
For the same line: <code>body.response.trade_offers_received.forEach</code>

**Comment by scholtzm** [comment]
Yes, of couse but if you dump both into console (or use a debugger), you will see there's a lot more information in those 2 objects and you might find your answer there.

**Comment by bercik809** [comment]
Okay, i have error from debugger. It's: <code>Error: connect ETIMEDOUT</code>

**Comment by bercik809** [comment]
What can I do with this?

**Comment by bercik809** [comment]
Is it a problem with steam servers?

**Comment by scholtzm** [comment]
Yep, in 95% cases it's their servers being poop.

**Comment by bercik809** [comment]
So, Is there any solution of this problem?
