### ISSUE TITLE
Returning items if getOffer()/getItems() fails

### ISSUE THREAD

**Issue by mikehhhhhhh** [steam-forward/node-steam-forum#41]
Some times when accepting a trade offer, the trade is accepted but then getOffer() or getItems() fails. 

Seeing as I'm getting the item id's from these calls, is there any easy way to send back the exact items from this trade offer?

**Comment by pmk010** [comment]
Before accepting the offer iterate through the sender's inventory to match the assetid to the id. Then store the defindex/market name (whatever property identifies the item but won't change). Then you can accept the offer and in the case getItems fails for you, you can reverse the process. Match the defindex/market name then get the (asset)id and finally create the offer to send back.
