### ISSUE TITLE
Can't read sentry 

### ISSUE THREAD

**Issue by dragonbanshee** [steam-forward/node-steam-forum#42]
It seems that the node-steam update makes it unable/changed it so that sentry files are handled in a completely different way. I am not unable to read sentry files to login, and must rely on steamguard, which is quite annoying. 

My code for writing the sentry: http://pastebin.com/BRvCR6Mx

And for reading them/logging in: http://pastebin.com/kzUMwMG7

It recognizes that the file is there (since I have an fs.existsSync at the beginning), but it is unable to read the sentry and I get AccountLogonDenied.

Any help would be appreciated. Thanks.

**Comment by PokeRwOw** [comment]
I got the same issue, always need the steam guard code. It's really annoying ^^

**Comment by scholtzm** [comment]
For the completeness sake, answered here: https://github.com/seishun/node-steam/issues/203#issuecomment-124813886

**Comment by dragonbanshee** [comment]
Got it finally, thanks!
