### ISSUE TITLE
Node-Trade-Offers; makeOffer, is it possible to pass trade link?

### ISSUE THREAD

**Issue by GuruFraser** [steam-forward/node-steam-forum#43]
So Looking at the API for node trade offers, it appears that when making an offer, it isn't possible to send over the trade url manually. I see it automatically finds one, but does it load the exact one steam provides? I'm just looking over some code I've done and it seems to work for some and not others, even while their inventory is public.

So question is can I pass the trade link in, if not can we get this added as a feature?

**Comment by scholtzm** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers#makeofferoptions-callback

> `accessToken` (optional) is a token from the public Trade URL of the partner
