### ISSUE TITLE
makeOffer question

### ISSUE THREAD

**Issue by bercik809** [steam-forward/node-steam-forum#45]
I have question, Can I send <code>itemsFromMe</code> in one offer? If I use <code>makeOffer</code> I receive all of items but it's not one offer.

**Comment by andrewda** [comment]
`itemsFromMe` should be an array of item objects. That way you can send multiple items in one trade offer.

**Comment by bercik809** [comment]
I have that: 
<code>itemsFromMe: [{ appid: 730, contextid: 2, amount:1, assetid: items[i].id}]</code>
And then I have multiple trade offers.

**Comment by bercik809** [comment]
Okay I know what i doing wrong.
