### ISSUE TITLE
webSessionID

### ISSUE THREAD

**Issue by MajorErection** [steam-forward/node-steam-forum#46]
I'm not sure if this has been asked anywhere but is there a replacement for 'webSessionID' and what is it because I can't get node-steam-trade to work

**Comment by scholtzm** [comment]
You probably want to use this: https://github.com/Alex7Kom/node-steam-weblogon

**Comment by MajorErection** [comment]
thanks! but will this be a temporary fix or will this be permanent?

**Comment by scholtzm** [comment]
This isn't a fix since nothing is broken.

The `webLogOn` method has been removed from node-steam so you either code your own (which is fairly easy) or you use something like the module I linked above (which is easier).

**Comment by MajorErection** [comment]
I didn't mean fixed but re-added back into node-steam but thanks anyways
