### ISSUE TITLE
SteamWebLogOn error

### ISSUE THREAD

**Issue by SmokedPotato** [steam-forward/node-steam-forum#47]
I followed [storehouse](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/storehouse.js) for the weblogon but I'm getting this error

buffer.js:68
    throw new TypeError('must start with number, buffer, array or string');
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:68:11)
    at SteamWebLogOn.webLogOn (C:\nodebot\node_modules\steam-weblogon\index.
js:25:54)

here is my code

      steamWebLogOn.webLogOn(function(sessionID, newCookie){
             getSteamAPIKey({
                 sessionID: sessionID,
                 webCookie: newCookie,
                 APIKey: APIKey
             });
        });

**Comment by scholtzm** [comment]
steamWebLogOn.webLogOn(function(sessionID, newCookie){
         getSteamAPIKey({
             sessionID: sessionID,
             webCookie: newCookie,
             APIKey: APIKey // this is surely wrong
         });
    });

You are probably calling webLogOn before you logged in. Plus the code you posted doesn't look correct.
