### ISSUE TITLE
Bot is not available to trade

### ISSUE THREAD

**Issue by MajorErection** [steam-forward/node-steam-forum#48]
Bot Erection is not available to trade. More information will be shown to Bot Erection if they invite you to trade.

I got this error today but didn't have this problem yesterday, is there a way I can find out what is causing the error?

**Comment by MajorErection** [comment]
or maybe just a way I can log the error message steam gave to my bot

**Comment by scholtzm** [comment]
If you log in to your bot via regular Steam client, are you able to trade?

**Comment by MajorErection** [comment]
yeah it works fine through the steam client, I'm guessing it has something to do with steamguard but is there a way I can log the error message given by steam? I don't see anything I can use in node-steam or maybe I'm missing something

**Comment by scholtzm** [comment]
node-steam is omitting certain properties:

* implementation: https://github.com/seishun/node-steam/blob/master/lib/handlers/trading/index.js#L61
* actual message: https://github.com/seishun/node-steam/blob/master/lib/handlers/trading/index.js#L61

For now, the only way is to create your own message handler.

**Comment by MajorErection** [comment]
I don't know how to create my own message handler since I'm pretty novice in programming but I'll give it a shot anyways, thanks a lot :)

**Comment by dragonbanshee** [comment]
For handling custom messages you can use 
```javascript
steamClient.on('message', function(header, body, callback) { ... }); 
```

https://github.com/seishun/node-steam#messagesend
