### ISSUE TITLE
web authentication 403, retrying

### ISSUE THREAD

**Issue by KappyKapy** [steam-forward/node-steam-forum#51]
i have this error, bot spammed - "web authentication 403, retrying" and bot dont accept trade.

**Comment by bercik809** [comment]
SteamGuard I think.

**Comment by KappyKapy** [comment]
bot connect and accept trades, but after 1 game (jackpot) i have this error

**Comment by scholtzm** [comment]
Cookies might have expired.

**Comment by KappyKapy** [comment]
"Cookies might have expired." how can I check?

**Comment by scholtzm** [comment]
Call `webLogOn` or whatever function you use to retrieve cookies and use those.

**Comment by KappyKapy** [comment]
can you try fix that to me for money? Im not a programmist, and dont have programmist's ...

**Comment by KappyKapy** [comment]
team.on('loggedOn', function(result) {
	console.log('Logged in!');
	steam.setPersonaState(Steam.EPersonaState.LookingToTrade);
	steam.addFriend("76561198133226853");
	steam.sendMessage(admin,"Я включился!");
});

steam.on('webSessionID', function(sessionID) {
	globalSessionID = sessionID;
	steam.webLogOn(function(newCookie) {
		offers.setup({
			sessionID: sessionID,
			webCookie: newCookie
		}, function(err) {
			if (err) {
				throw err;
			}
			setInterval(CheckTimer,1000);
		});
	});
});
steam.on('friendMsg', function(steamID, message, type) {
	if(type != Steam.EChatEntryType.ChatMsg) return;
	if(steamID == admin) {
		if(message.indexOf("/sendallitems") == 0) {
			offers.loadMyInventory({
				appId: 730,
				contextId: 2
			}, function(err, items) {
				if(err) {
					steam.sendMessage(steamID, 'Не могу загрузить свой инвентарь, попробуй ещё раз');
					steam.webLogOn(function(newCookie) {
						offers.setup({
							sessionID: globalSessionID,
							webCookie: newCookie
						}, function(err) {
							if (err) {

I have many webLogOn in code

**Comment by jhartzell** [comment]
This issue is typically caused by steam timeouts, it will also happen when steam is down, you should look at https://steamstat.us/ while it is occurring and see if steam community is down, or if the WebAPI is down..I have never seen this happen while steam is online. Let me know what you find!

**Comment by Frederik123** [comment]
KappyKapy , you can write me an email - for_frederik@mail.ru ?
