### ISSUE TITLE
Error Accepting tradeoffer, but success accept.

### ISSUE THREAD

**Issue by overheader** [steam-forward/node-steam-forum#55]
Hi. I have a problem.
Sometimes, when tradeoffer is accepting - steam send error (Please try again later. (11), Please try again later. (16)), but tradeoffer accepted. 
How to solve this problem?
P.S. declineOffer does not help

**Comment by scholtzm** [comment]
Yep, that's normal and happens constantly with large offers. There's not much you can do about it other than periodically check the trade status.

**Comment by pmk010** [comment]
I have a few questions if you would be kind enough to answer them: 
How larger size do the trade offers have to be for this to happen would you say? 
When you say check the trade status does that mean in some cases the offer is in fact accepted?
And lastly, how many attempts does it take for large offers to be accepted?

Thanks in advance :)

**Comment by scholtzm** [comment]
1. No idea and I don't think there's a specific number. But try 100 items and it will fail consistently.
2. The trade offer is often accepted couple seconds/minutes later after the error. The more items in the trade offer, the bigger the gap.
3. One attempt is sufficient most of the time.

**Comment by pmk010** [comment]
Thanks for the information!

**Comment by scholtzm** [comment]
Sending should be always instant.
