### ISSUE TITLE
error sending your trade offer. Please try again later. (15).

### ISSUE THREAD

**Issue by DenisMd** [steam-forward/node-steam-forum#59]
Hello, everyone. I have some problem with bot, when i make Offer with user which no friend to bot,then i got this error: There was an error sending your trade offer. Please try again later. (15). If i make offer with user, which friend with bot, then all right. Sorry for my English)

**Comment by scholtzm** [comment]
`AccessDenied = 15`

Are you using the token?

**Comment by DenisMd** [comment]
Nope, what is that?

**Comment by scholtzm** [comment]
[makeOffer(options[, callback])](https://github.com/Alex7Kom/node-steam-tradeoffers#makeofferoptions-callback), see `accessToken`.

And yes, the user has to give it to you.

And no, there is no other way of getting the token.

**Comment by DenisMd** [comment]
Ok, thanks. And last question, format is a string or json object?

**Comment by scholtzm** [comment]
String.

**Comment by DenisMd** [comment]
Thanks. closed.
