### ISSUE TITLE
Error: There was an error accepting this trade offer.  Please try again later. (24)

### ISSUE THREAD

**Issue by StevePavlin** [steam-forward/node-steam-forum#60]
I am getting this from accepting a trade offer on a bot. I am able to accept the trade offer on the web, but this only occurs when the bot trys to accept it. The bot logs in fine and gets offers fine. Any ideas on how to troubleshoot this?

**Comment by scholtzm** [comment]
Seems like the SteamGuard is blocking you. Have you waited 7 days?

**Comment by StevePavlin** [comment]
Error seemed to have disappeared overnight. I think it might have been a steam guard issue.
