### ISSUE TITLE
Multiple bots

### ISSUE THREAD

**Issue by dolanmiu** [steam-forward/node-steam-forum#62]
To have multiple bots, would I create multiple instances of steamClient and steamUser,

OR:

ONE instance of steamClient, and multiple steamUsers?

I have a method:

exports.createBot = function () {
    'use strict';

    var steamClient = new Steam.SteamClient(),
        steamUser = new Steam.SteamUser(steamClient);

    steamClient.offers = new SteamTradeOffers();
    steamClient.connect();

    events.bindEvents(steamClient);
    return steamClient;
};

**Comment by scholtzm** [comment]
You'll need multiple clients as well as multiple handlers of course.

**Comment by dolanmiu** [comment]
Ok, does that mean, I would need multiple SteamFriends, SteamTradeOffers etc?

Would you say the best way to handle all of this is to put each instance as an array of objects?

like:

var bots: [{
    client:
    user: 
    tradeOffers:
    friends:
}]

then to access one bot out of the many, you do bots[0].client etc.

you get the idea

**Comment by scholtzm** [comment]
Yes, that could work.

**Comment by dragonbanshee** [comment]
I'm not sure if this would work, but you could maybe use some sort of inheritance to shorten your code by using [util.inherits](https://nodejs.org/api/util.html#util_util_inherits_constructor_superconstructor).

**Comment by BenWoodford** [comment]
The way I did multiple bots was to have a masterbot.js which handles keeping them up, spinning up new ones, etc, and a slavebot.js which I run using the NodeJS Cluster library. Keeps things nice and separate and means one bot can't crash all of them.

**Comment by dragonbanshee** [comment]
I was actually inspired by this last night and created [node-steam-parentbot](https://github.com/dragonbanshee/node-steam-parentbot) this morning.

**Comment by andrewda** [comment]
@dragonbanshee That looks like it could be very useful! Thanks!

**Comment by dolanmiu** [comment]
@dragonbanshee you are AWESOME <3
I will be one of your first customers

**Comment by dolanmiu** [comment]
@dragonbanshee why is there no _onTrade() event handler

**Comment by dragonbanshee** [comment]
I decided not to do trading since I figured it would be best left to the user. You could add your own 'tradeProposed' listener by doing the following

```javascript
Bot.steamTrading.on('tradeProposed', function(tradeID, steamID) {
    //any trading stuff here you want
});
```
This is the one that is included with the examples. If you want to add a steam trade listener,
```javascript
var SteamTrade = require('steam-trade');
Bot.trade = new SteamTrade();

Bot.trade.on('offerChanged', function(item, bool) {
    //however you want to handle items
});
```

**Comment by graycatfromspace** [comment]
another method is to create a manager script and use socket io to interface with the bots.
