### ISSUE TITLE
When passin string through variable than function not working 

### ISSUE THREAD

**Issue by rahulchhlotre** [steam-forward/node-steam-forum#63]
Hello

like this i am adding valeu  :- var html = "{appid: 730, contextid: 2, amount: 1, assetid: 2883267603}";
and error is :- Error: There was an error sending your trade offer. Please try again later. (20)

please check code :- 
var receivedData = data;  
    
  var obj = new Array();
  var arr = receivedData.split(',');

  var arrayLength = arr.length;
  //console.log(arrayLength);
  var newarr = [];
  var keyarr = [];
  for(var x=0; x<arrayLength;x++){
    var splittedString = arr[x].split(':'); 

    var key = splittedString[0];
    if(key=='steamid' || key=='token'){
      keyarr[key] = splittedString[1];
    }else{
      newarr[key] = splittedString[1];
    }
    
  }

function offerItems() {
var defaultItem = 'item';
  for(var j=1; j<=items_value_count;j++){
      var item_key = defaultItem+j;
      html += '{'
                  +'appid: 730,'
                   + 'contextid: 2,'
                   + 'amount: 1,'
                   + 'assetid: "'+ newarr[item_key] +'"},';
  }
  steamid = keyarr['steamid'];
  token = keyarr['token'];
  
  //console.log(items_value_count);
  //console.log("Steam ID"+steamid);
  //console.log("token ID"+steamid); 
  // return false;
  offerItems();
    
    };
  });

var refreshIntervalId;
function offerItems() {
  offers.loadPartnerInventory({
    appId: 730,
    contextId: 2,
  partnerSteamId: steamid
  }, function(err, items) {
      offers.makeOffer ({
        partnerSteamId: steamid,
    accessToken: token,
        itemsFromMe: [],
        itemsFromThem: [          
            html
        ],
        message: 'This is test'
      }, function(err, response) {
        if (err) {
          throw err;
        }
    console.log(response);
    
    result = response.tradeofferid;
    
        res.write(result);
    
    refreshIntervalId = setInterval(function()
    {
    checkOffer();
    },1000);
        
    
      });
  });
  
}

when i am passing html variable than function not working but if am adding same data of variable than function working.

Thanks for help

**Comment by jwigley** [comment]
Looks like your `html` variable is a string, but it should be an object.

You might be better off using the output `items` from `loadPartnerInventory` to build up your array for `itemsFromThem`.

**Comment by rahulchhlotre** [comment]
Hello jwigley
Thanks for reply, 

can you show me code example of :- output items from loadPartnerInventory to build up your array for itemsFromThem.
Thanks

**Comment by jwigley** [comment]
Something like this should do it:

```node
offers.loadPartnerInventory({
...
, function(err, items) {
    var itemsArray = new Array();
    items.forEach(function(item) {    
 
         // some logic here to skip item if you don't want to add it. check item type etc.
         ....

        // trim items to only stuff we need
        itemsArray.push({
          'appid': item.appid,
          'contextid': item.contextid,
          'amount': item.amount,
          'assetid': item.id
        });
    }); 

    offers.makeOffer ({
        partnerSteamId: steamid,
        accessToken: token,
        itemsFromMe: [],
        itemsFromThem: itemsArray,
    });
...
```
