### ISSUE TITLE
Steam respond error but accept trade?

### ISSUE THREAD

**Issue by MaTyyyJ** [steam-forward/node-steam-forum#66]
Hi.

I have a problem. I make a condition that checks if an error occurs while accepting a trade, but the steam returns various errors 2,16,11 but trade is accepted and i gets items. If I removed the error checking am afraid that the offer will be mirrored in the database.

I dont know how to repair it :(

**Comment by scholtzm** [comment]
Yep, welcome to Steam. The behaviour you are experiencing is 'correct'.

**Comment by MaTyyyJ** [comment]
So, how to check if trade is really accepted?

**Comment by scholtzm** [comment]
You can check the trade state.

**Comment by graycatfromspace** [comment]
I have this same issue and the funny thing is the old library still gave you the offer id if you got this error.
