### ISSUE TITLE
Can't get around error 26

### ISSUE THREAD

**Issue by Ax6** [steam-forward/node-steam-forum#68]
I'm getting error 26 from steam when sending a trade offer, but not a generic trade offer. It happens only if I make the offer to a particular steamid. Bot works fine with anybody, but somehow it constantly gets error 26 when sending offer to this particular steam account.

So far
- Sending a trade offer to this account from browser, using a bot account, works fine.
- Tried with 2 different bots, both are getting error 26.
- Logged trade offer request and verified form contents, everything seems fine, plus item ids exist, I manually checked with the steam api.
- Tried to manually set cookies I had on browser, no success.

I really can't get around this problem, any suggestion?

**Comment by dragonbanshee** [comment]
I believe 26 means that the other users inventory is full, so that could be it considering it only happens with 1 person.

**Comment by Ax6** [comment]
Partner inventory is not full.

**Comment by graycatfromspace** [comment]
https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd

**Comment by Ax6** [comment]
.. revoked.. that was helpful

**Comment by dragonbanshee** [comment]
@graycatfromspace I never realized that the eresults were for trade offers either, thanks!

Yeah no idea what revoked means.

**Comment by graycatfromspace** [comment]
funny part is now im getting this and have no idea what causes it xD

**Comment by graycatfromspace** [comment]
ok i found a way to fix it, you need to launch the game to have it able to send the items for some reason.

**Comment by Ax6** [comment]
Alright, I'll try that

**Comment by graycatfromspace** [comment]
started getting this issue alot still cant seem to pin it down.

**Comment by graycatfromspace** [comment]
seems to be directly related to assetid's

**Comment by Axumata** [comment]
Try casting assetid of your item to string. It worked for me.

**Comment by 0-elip** [comment]
i know this is far past closed, but neither of the above mentioned fixes work. my assetid is already a string
