### ISSUE TITLE
Error 42 accepting?

### ISSUE THREAD

**Issue by StevePavlin** [steam-forward/node-steam-forum#71]
Hi, I am testing a website that takes a large volume of trade offers. About 1/10 offers get:

 Error: There was an error accepting this trade offer.  Please try again later. (42)

By the eresult.steamd:

NoMatch = 42;

This is when I send some items from one bot to another as an offer, then accept the offer on the 2nd bot. When I check the trade offers page on the bot I see:

Trade Offer Canceled 26 Aug, 2015

Anyone have any ideas?

**Comment by scholtzm** [comment]
Is your bot1 cancelling the offer?

Afaik, "NoMatch" means there was no matching trade offer ID among your pending offers.
