### ISSUE TITLE
error accepting this trade  offer. 24

### ISSUE THREAD

**Issue by jensej** [steam-forward/node-steam-forum#72]
Fri Aug 28 2015 13:49:14 GMT+0200 (CEST) - Error: There was an error accepting this trade                     offer.  Please try again later. (24)
/var/www/node_modules/steam/node_modules/bytebuffer/dist/ByteBufferNB.js:1                    749
                throw TypeError("Illegal str: Not a string");
                      ^
TypeError: Illegal str: Not a string
    at TypeError (native)
    at module.exports.ByteBufferPrototype.writeCString (/var/www/node_modu                    les/steam/node_modules/bytebuffer/dist/ByteBufferNB.js:1749:23)
    at SteamFriends.sendMessage (/var/wwwnode_modules/steam/lib/handlers/                    friends/index.js:63:11)
    at log (/var/www/node_modules/steam-tradeoffers/donation_bot.js:197:16                    )

Someone Could tell why?

**Comment by scholtzm** [comment]
Would be useful if you posted the piece of code that is causing this:

`SteamFriends.sendMessage (/var/wwwnode_modules/steam/lib/handlers/ friends/index.js:63:11)`

**Comment by jensej** [comment]
It is orginal example from github:
here my file:
http://pastebin.com/raw.php?i=1r9peZYc

**Comment by scholtzm** [comment]
Well, looks like you are passing error object instead of a string.

**Comment by jensej** [comment]
why? I only copied orginal code. It should works.

**Comment by scholtzm** [comment]
Bugs happen.

You can easily check if it's an actual string.

**Comment by Alex7Kom** [comment]
Seems like I overlooked this. Indeed an error object must be converted to string for `sendMessage`. Updated: https://gist.github.com/Alex7Kom/d764ef2925060c4e7c27

**Comment by jensej** [comment]
Now there is something like this
Logged in!
Fri Aug 28 2015 19:25:45 GMT+0200 (CEST) - Error: 403

**Comment by jensej** [comment]
Items to receive: Operation Phoenix Weapon Case (Base Grade Container)

Fri Aug 28 2015 22:31:49 GMT+0200 (CEST) - Error: There was an error accepting this trade offer.  Please try again later. (24)
Fri Aug 28 2015 22:31:49 GMT+0200 (CEST) - Offer 667656240 accepted

**Comment by dragonbanshee** [comment]
24 is steamguard I believe.

**Comment by jensej** [comment]
I'm trying to delete sentry and start new session but its still this same error.
Someone know why?

**Comment by Alex7Kom** [comment]
Obviously, every new sentry file is like a new device for Steam, so you should wait for 7 days before you'll be able to trade.

**Comment by jensej** [comment]
thanks

**Comment by jensej** [comment]
I try use my friend steam accout. First login. And this same error.

**Comment by jensej** [comment]
is a faster solution?
