### ISSUE TITLE
I will send a trade but half the items will go missing.

### ISSUE THREAD

**Issue by broomop** [steam-forward/node-steam-forum#73]
AUG | Condemned (Field-Tested)/MAG-7 | Heaven Guard (Minimal Wear)/SG 553 | Damascus Steel (Field-Tested)/Sticker | dennis | Cologne 2015/Sticker | dennis | Cologne 2015/Sticker | dennis | Cologne 2015/Sticker | dennis | Cologne 2015/Sticker | Xizt | Cologne 2015/Sticker | Xizt | Cologne 2015/StatTrak™ Five-SeveN | Nightshade (Factory New)/AK-47 | Cartel (Field-Tested)/Desert Eagle | Conspiracy (Minimal Wear)/Glock-18 | Water Elemental (Field-Tested)/AK-47 | Redline (Field-Tested)/AK-47 | Redline (Field-Tested)

for example will miss out the last 3 items.

the code is like this:

for(var i=0; i < row.length; i++) {
				var gameid = row[i].id;
				var sendItems = (row[i].items).split('/');
				var item=[],num=0;
				for (var x = 0; x < itemscopy.length; x++) {
					for(var j=0; j < sendItems.length; j++) {
						if (itemscopy[x].tradable && (itemscopy[x].market_name).indexOf(sendItems[j]) == 0) {
							sendItems[j] = "hgjhgnhgjgnjghjjghjghjghjhgjghjghjghngnty";
							itemscopy[x].market_name = "fgdfgdfgdfgdfgfswfewefewrfewrewrewr";
							item[num] = {
								appid: 730,
								contextid: 2,
								amount: itemscopy[x].amount,
								assetid: itemscopy[x].id
							}
							num++;
						}
					}
				}

why would this miss out items? i am using an older version of the steam-tradeoffers because the new one fails to accept items im not sure why. But you think using an older version could be the issue its not working???

**Comment by dragonbanshee** [comment]
You are using stolen csgofast code, so I don't know why you expected better. You would be better off writing your own bot.

**Comment by broomop** [comment]
its ok i done it thanks for your help.

**Comment by BryanK97** [comment]
@broomop what was the issue with this bit of code?

**Comment by BryanK97** [comment]
@broomop was it a problem with your classid's when you went to try and send it?
