### ISSUE TITLE
Load Partner Inventory error

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [steam-forward/node-steam-forum#74]
This error happens in steam-tradeoffers

I have a successful login of a 'bot' account. I have a user account that logged in and have the steamid.
I am trying to retrieve the user accounts inventory.
```
offers.loadPartnerInventory({
		appId: 730,
		contextId: 2,
		partnerSteamId: userId
	},function(err, items){
		callback(err, items);
	});
```
At line 398 of the loadInventory function is where the fail happens (steam-tradeoffers/index.js).

There is no body.rgInventory, body.rgDescriptions or body.rgCurrency. The only things in the body are:
0 = 'success'
1= false

The only error is invalid response so not sure what I am missing or what is going wrong. Any ideas? Thanks for the help!

**Comment by andrewda** [comment]
Is the user's account private? What is the value of `userId`?

**Comment by BenjaminNeilDavis** [comment]
@andrewda The user account is not private and the value of userId is the users steam id. Thanks for the quick response

**Comment by jwigley** [comment]
The code looks fine. So assuming setup() has completed successfully before your call to loadPartnerInventory, then I'd guess it's something related specifically to that user. Can you test with another steam id?

**Comment by dragonbanshee** [comment]
Try making the numbers strings instead:

```javascript
offers.loadPartnerInventory({
    appId: '730',
    contextId: '2',
    partnerSteamId: userId
}, function(e, response) {
    callback(e, response);
});
```javascript


This works for me, not sure why. Also make sure the userId is friends with your bot.
