### ISSUE TITLE
Node-Steam with Heroku

### ISSUE THREAD

**Issue by dolanmiu** [steam-forward/node-steam-forum#75]
Because Heroku has some dynamic IP address jazz going on, it keeps on changing the IP address of my server heroku app, which means Steam will always think we are logging in from a different location, so I must always enter in the Steam Guard Code every few minutes. It is quite annoying.

Is there any way to resolve this?

**Comment by jwigley** [comment]
Make sure you are saving/logging in with the sentry correctly. With the sentry, it should work regardless of the heroku server IP. I have successfully run node-steam on heroku without requiring any specific changes for dynamic IPs.

**Comment by dolanmiu** [comment]
Could you give me an example? It runs perfectly find on my localhost:9000, but when I deploy it on heroku, it keeps on asking for steam guard every 20 mins or so...

But thanks for that reply, a little bit relieved. I was looking into some crazy plans to make the IP static

**Comment by jwigley** [comment]
@Alex7Kom provides an example: https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/storehouse.js

@dragonbanshee also posted a similiar example: https://github.com/steam-forward/node-steam-forum/issues/33

**Comment by dolanmiu** [comment]
```
Sep 02 04:48:03 app/web.1:  { [Error: ENOENT, no such file or directory '/app/server/bots/manager/sentryfiles/5571a1d6ccc3070300164d33'] 
Sep 02 04:48:03 app/web.1:    errno: -2, 
Sep 02 04:48:03 app/web.1:    code: 'ENOENT', 
Sep 02 04:48:03 app/web.1:    path: '/app/server/bots/manager/sentryfiles/5571a1d6ccc3070300164d33', 
Sep 02 04:48:03 app/web.1:    syscall: 'open' } 
```

I found out the issue, my sentry file is being saved, but however, the saved sentry file is being lost.

This is my code to save the sentry file:

```
fs.writeFile(__dirname + '/sentryfiles/' + botId, sentry.bytes, function (err) {
            if (err) {
                console.error('Failed to save sentry file');
                console.error(err);
            } else {
                console.info('Saved sentry file');
                callback({
                    sha_file: getSHA1(sentry.bytes)
                });
            }
        });
```

Whenever it tries to save the sentry file with the above code, I get this response:

```
Sep 02 04:51:06 app/web.1:  Connected to steam 
Sep 02 04:51:06 app/web.1:  Steam gave a sentry file back for bot: 5571a1d6ccc3070300164d33 
Sep 02 04:51:06 app/web.1:  Saved sentry file 
```

So in other words... it saves, but then something, or someone deletes it?? Spooky...

**Comment by dolanmiu** [comment]
Could this be the reason?

https://stackoverflow.com/questions/11246736/after-git-push-heroku-uploaded-files-on-heroku-are-lost

> With Heroku’s ephemeral filesystem, any information written to a dyno’s filesystem will be lost when the dyno is restarted. Instead, Heroku recommends backing services. For file and media storage, Amazon’s Simple Storage Service (S3) is a great solution.

**Comment by dragonbanshee** [comment]
Check that you are actually reading the same directory that it's being written to. Also after its written, go to the directory to see that it's actually been written.  Both of these have been issued for me.

**Comment by dolanmiu** [comment]
Is there a way to check the files in heroku?

**Comment by jwigley** [comment]
It does look like you can't rely on storing files in Heroku.

https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

> During the dyno’s lifetime its running processes can use the filesystem as a temporary scratchpad, 
> but no files that are written are visible to processes in any other dyno and any files written will be
> discarded the moment the dyno is stopped or restarted.

Do you have a database you could store the sentry in instead?

**Comment by dolanmiu** [comment]
Yes, i resolved the issue yesterday by storing the sentry file in a database :) 

thanks all, hopefully this will be useful for others. I am surprised no one came across this until now
