### ISSUE TITLE
Make offer (15)

### ISSUE THREAD

**Issue by jensej** [steam-forward/node-steam-forum#76]
offerbot.js:72
          throw err;
                ^
Error: There was an error sending your trade offer.  Please try again later. (15)

Code:
function offerItems() {
  offers.loadMyInventory({
    appId: 730,
    contextId: 2
  }, function(err, items) {
    var item;
    // picking first tradable item
    for (var i = 0; i < items.length; i++) {
      if (items[i].tradable) {
        item = items[i];
        break;
      }
    }
    // if there is such an item, making an offer with it
    if (item) {
      offers.makeOffer ({
        partnerSteamId: admin,
        itemsFromMe: [
          {
            appid: 730,
            contextid: 2,
            amount: 1,
            assetid: item.id
          }
        ],
        itemsFromThem: [],
        message: 'This is test'
      }, function(err, response) {
        if (err) {
          throw err;
        }
        console.log(response);
      });
    }
  });
}

**Comment by jwigley** [comment]
Do you have a specific question?

Error 15 has been discussed previously:
     - https://github.com/Alex7Kom/node-steam-tradeoffers/issues/41
     - https://github.com/steam-forward/node-steam-forum/issues/59

Are you friends with the person you are trading too? If not you need the access token.

I've formatted your code ( http://jsbeautifier.org/ ) so others can actually read it.

```js
function offerItems() {
    offers.loadMyInventory({
        appId: 730,
        contextId: 2
    }, function(err, items) {
        var item;
        // picking first tradable item
        for (var i = 0; i < items.length; i++) {
            if (items[i].tradable) {
                item = items[i];
                break;
            }
        }
        // if there is such an item, making an offer with it
        if (item) {
            offers.makeOffer({
                partnerSteamId: admin,
                itemsFromMe: [{
                    appid: 730,
                    contextid: 2,
                    amount: 1,
                    assetid: item.id
                }],
                itemsFromThem: [],
                message: 'This is test'
            }, function(err, response) {
                if (err) {
                    throw err;
                }
                console.log(response);
            });
        }
    });
}
```

**Comment by jensej** [comment]
partnerAccountId: 765....14, I have changed from admin.

yes, partner is my friend. I check previously discussed. Do you have others ideas?

**Comment by scholtzm** [comment]
`partnerAccountId` and `partnerSteamId` are different. Seems like you are using accountID and supplying steamID.

**Comment by jensej** [comment]
I tried both. 
<pre>

/node_modules/long/dist/Long.js:191
        if ((p = str.indexOf('-')) > 0)
                     ^
TypeError: undefined is not a function
    at Function.Long.fromString (/var/www/steam.jensej.pl/node_modules/steam-tradeoffers/node_modules/long/dist/Long.js:191:22)
    at toAccountId (/var/www/steam.jensej.pl/node_modules/steam-tradeoffers/index.js:342:15)
    at SteamTradeOffers.makeOffer (/var/www/steam.jensej.pl/node_modules/steam-tradeoffers/index.js:240:42)
    at /var/www/steam.jensej.pl/node_modules/steam-tradeoffers/offerbot.js:58:20
    at SteamTradeOffers.<anonymous> (/var/www/steam.jensej.pl/node_modules/steam-tradeoffers/index.js:409:7)
    at Request.self.callback (/var/www/steam.jensej.pl/node_modules/steam-tradeoffers/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/var/www/steam.jensej.pl/node_modules/steam-tradeoffers/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/var/www/steam.jensej.pl/node_modules/steam-tradeoffers/node_modules/request/request.js:1019:12)
root@vps133007:/var/www/steam.jensej.pl/node_modules/steam-tradeoffers# /node_modules/long/dist/Long.js:191
        if ((p = str.indexOf('-')) > 0)
-bash: /node_modules/long/dist/Long.js:191: Nie ma takiego pliku ani katalogu
root@vps133007:/var/www/steam.jensej.pl/node_modules/steam-tradeoffers#         if ((p = str.indexOf('-')) > 0)

</pre>

**Comment by jensej** [comment]
Problem is when i tried sent offer to not my friend. I tried use accessToken in this form:
<pre>
if (item) {
            offers.makeOffer({
                partnerAccountId: 191123123,
               accessToken: 'https://steamcommunity.com/tradeoffer/new/?partner=191123123&token=fahtNZzggF',
                itemsFromMe: [{
                    appid: 730,
                    contextid: 2,
                    amount: 1,
                    assetid: item.id
                }],
                itemsFromThem: [],
                message: 'This is test'
            }, function(err, response) {
                if (err) {
                    throw err;
                }
                console.log(response);
            });
        }
</pre>
but I have again error::
<pre>

Error: There was an error sending your trade offer.  Please try again later. (15)

</pre>

**Comment by Axumata** [comment]
accessToken is not "https://steamcommunity.com/tradeoffer/new/?partner=191123123&token=fahtNZzggF"

it's "fahtNZzggF"

**Comment by jensej** [comment]
omg. Thanks.
