### ISSUE TITLE
Getting an error with no message

### ISSUE THREAD

**Issue by bgr11n** [steam-forward/node-steam-forum#78]
Hello!

Can you please help me, I'm getting an error when I'm trying to make a trade offer, or load my inventory, but err object in callback is empty. Can it be related to thing that it's a new login? Or how can i be sure, just wait 1-2 weeks?

Thanks for help!

**Comment by scholtzm** [comment]
How do you know you are getting error if error object is empty?

Loading inventory is not directly related to SteamGuard btw.

**Comment by bgr11n** [comment]
@scholtzm Thanks for your reply, I'm doing something like this on `logOnResponse` event for `steamClient`:

```javascript
      offers.loadMyInventory({
        appId: 570,
        contextId: 2
      }, function(err, items) {
        if (err) {
          console.log({ success: false, errors: err });
        } else {
          console.log({ success: true, response: items });
        }
      });
```
And the `items` object is undefined

**Comment by scholtzm** [comment]
Have you called `setup()` before calling `loadMyInventory()`?
Have you tried loading other than the CSGO inventory?

**Comment by bgr11n** [comment]
Nope, but I did it for `makeOffer`, I'll try it with `loadMyInventory`.
570 must be Dota 2, I missing something?

**Comment by scholtzm** [comment]
How about the examples here: https://github.com/Alex7Kom/node-steam-tradeoffers/tree/master/examples

Do those work for you?

**Comment by bgr11n** [comment]
I'll try it now.

**Comment by bgr11n** [comment]
You know it must be something with steam, because I've tried to run my code, and it works. xD

Anyway thanks for help!

**Comment by bgr11n** [comment]
I have one more questions I need to do all tradeoffer requests inside `steamClient` `logOnResponse` event? Or i can separate them somehow?

Thanks!

**Comment by scholtzm** [comment]
You can and you should separate them.

**Comment by bgr11n** [comment]
Ok, I figured it out. And one last question, there always should be such chain:

`getSteamAPIKey` -> `offers.setup` -> `offers.loadMyInventory` or `offers.makeOffer` ?

**Comment by scholtzm** [comment]
Well, yes... that will work if you need to send an offer instantly after getting the API key.

However, if this chain is triggered each time by, let's say a chat message, this is a bad design.

**Comment by bgr11n** [comment]
@scholtzm Ok, thanks!
