### ISSUE TITLE
Keep getting error 26 Revoked when sending trade offer

### ISSUE THREAD

**Issue by Axumata** [steam-forward/node-steam-forum#79]
I keep getting 26 Revoked error while sending trade offers from my CS:GO bot, and I can't even figure out the conditions under which it happens, because some of the offers pass — but most do not. 
What can I do to figure out what causes that error?
Partner's inventory is definitely not full, and transferring even a single item fails.

**Comment by scholtzm** [comment]
Check out https://github.com/steam-forward/node-steam-forum/issues/68

**Comment by Axumata** [comment]
Figured it out. I typecasted assetid to string and it works like a charm.
