### ISSUE TITLE
[steam-tradeoffers]: Request bot keep track of when user accepted.

### ISSUE THREAD

**Issue by pede** [steam-forward/node-steam-forum#8]
I used offerbot code to make a request bot to requet a item from a user.
The bot works and can requet the item but i need to keep track of when user has accepted the item.

Hope somone can help me with this!
Thanks in advance!

**Comment by AardvarkMike** [comment]
node-steam has a tradeoffers event that fires when your number of active tradeoffers changes. 

I guess you could then use that to go and check with tradeoffer is no longer active.

**Comment by Alex7Kom** [comment]
The only way to do this is to poll Steam using `.getOffer()`. See https://github.com/Alex7Kom/node-steam-tradeoffers/issues/77

**Comment by AardvarkMike** [comment]
Does the number of active trade offers not change when one is accepted, Alex?

If not, I need to figure out why else tradeOffers() is getting fired twice :o

**Comment by Alex7Kom** [comment]
`tradeOffers` event of node-steam fires every time the number of trade offers you __recieved__ is changed (even if it became `0`). It has nothing to do with trade offers you sent by yourself.
