### ISSUE TITLE
Cant match item assetids

### ISSUE THREAD

**Issue by Marnas9** [steam-forward/node-steam-forum#80]
How can I check traded item classid and instanceid? I tried assetid but it changes after trade.
Tried:
result.id (Gives AssetID)
result.classid (Gives ClassID)
result.instanceid (Gives 0)
Why instanceid is giving 0?

**Comment by scholtzm** [comment]
`0` is a valid value for `instanceid`.

**Comment by Marnas9** [comment]
So how can you get unique id of CSGO item? I tried AssetID, but it changes after trade.

**Comment by jwigley** [comment]
These might be of some help:
https://www.reddit.com/r/SteamBot/comments/394o9d/understanding_item_ids/
https://www.reddit.com/r/SteamBot/comments/36lxmc/figuring_out_an_items_classid_and_assetid/
https://www.reddit.com/r/SteamBot/comments/3dthc2/assetid_instanceid_classid/
