### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by jensej** [steam-forward/node-steam-forum#84]
After accepted items, I have sth like this:
<pre>
/donation_bot.js:107
      body.response.descriptions.forEach(function (desc) {
                                ^
TypeError: Cannot read property 'forEach' of undefined

</pre>

here part of code:
<pre>

 if (
      body
      && body.response
      && body.response.trade_offers_received
    ) {
      var descriptions = {};
      body.response.descriptions.forEach(function (desc) {
        descriptions[
          desc.appid + ';' + desc.classid + ';' + desc.instanceid
        ] = desc;
      });

      body.response.trade_offers_received.forEach(function (offer) {
        if (offer.trade_offer_state !== 2) {
          return;
        }
</pre>

**Comment by jwigley** [comment]
Was get_descriptions option set?

https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#GetTradeOffer_.28v1.29

**Comment by jensej** [comment]
no,  how it should like be?

**Comment by jwigley** [comment]
The valve documentation implies descriptions will only returned if you set the get_descriptions option.

So In the options you are passing to getOffers, you need to add 'get_descriptions: 1'.

**Comment by jensej** [comment]
language - needed if get_descriptions is set, the language to use for item descriptions.
Thanks
