### ISSUE TITLE
Manually adding sessionid and cookie data results in 503

### ISSUE THREAD

**Issue by Netifriik** [steam-forward/node-steam-forum#85]
Hi, I'm trying to manually log-in through webLogon but when using my cookie data and sessionid I get a 503 error.

```
var myCookie = [
			'sessionid=xxx',
			'steamLogin=xxx',
			'steamLoginSecure=xxx'
		];
		offers.setup({
			sessionID: "xxx",
			webCookie: myCookie
		}, function(err) {
			if (err) {
				console.log('I failed logging the webSessionID', err);
				throw err;
			}
			console.log('webSessionID is completed. HF.');
		});
```

**Comment by scholtzm** [comment]
1. SessionID can be anything, just make sure they match.
2. The cookies you provide should not be url encoded.
3. Setup doesn't provide error: https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/index.js#L31

@Alex7Kom What's the callback argument in `setup` for? The code is synchronous after all so you [shouldn't need a callback](https://github.com/Alex7Kom/node-steam-tradeoffers#setupoptions-callback) to access trade offers.

**Comment by Netifriik** [comment]
1. Like anything random? I don't need to take the SessionID from steam?
2. So I should decode the cookie values for steamLogin and steamLoginSecure?

**Comment by scholtzm** [comment]
If by "steam" you mean `node-steam`, then this library doesn't even give you the sessionID.

1. Yes. [Random is good.](https://github.com/scholtzm/vapor/blob/master/lib/vapor.js#L212)
2. Yes, decode them first.

**Comment by Netifriik** [comment]
I'm using steam and steam-tradeoffers. By sessionID I mean the cookie value that is set when you login through steamcommunity. I want the webLogon to use an already existing "session" that can trade w/o waiting 7 days. I'm not even sure if it would work though.

**Comment by Alex7Kom** [comment]
@scholtzm Oh, my bad. `setup()` was async before 2.0.0 since it used to retrieve API key. Well, removing it now will be a breaking change for sure. But you are right anyway, there is no reason to use this callback anymore.

**Comment by scholtzm** [comment]
@Netifriik sessionID is just a random CSRF token. Whether it affects SteamGuard, I don't know. If you want to be safe, you can try to recycle all 3 values from your browser.

@Alex7Kom Yeah, that's pretty much what I thought.

**Comment by Netifriik** [comment]
When I let node steam get the cookies and sessionID the callback returns my console.log message. When I use my own cookies and the sessionID I got from the community website it skips the callback. Also after skipping the callback when trying to accept trade offers it throws 403 error.

**Comment by scholtzm** [comment]
`node-steam` doesn't provide cookies nor sessionID.

**Comment by Netifriik** [comment]
I assume that is part of `steam-tradeoffers`. I'll make an issue there.

**Comment by scholtzm** [comment]
You will get redirected right back here.

**Comment by Netifriik** [comment]
Ok. I fixed my https://github.com/steam-forward/node-steam-forum/issues/85#issuecomment-140061787 comment. It's now `steam-tradeoffers` instead. It also uses `steam-weblogon`.

Why does the code in my first post work if I let those two addons deal with the cookies and sessionid and not when I set them manually? I tried outputting the cookie data that `steam-weblogon`? fetches and the format looks the same.

**Comment by scholtzm** [comment]
Well, it's hard to tell how it works on their end. Cookies don't necessarily have to be portable.

**Comment by Netifriik** [comment]
When I replace the steamLogon values that I manually added with the ones that I outputted from `steam-weblogon`'s cookie object it works. But since those cookie values are new they have a 7-day trade lock. Maybe steam is detecting that the values used are not from the machine being used? Since I'm basically trying to take cookies from machine to another to avoid the trade lock.

**Comment by scholtzm** [comment]
Yep, that's what I was hinting at. That the cookies might not be portable.

**Comment by Netifriik** [comment]
So there's no way of evading the 7-day trading lock on a new machine? Even with the ssfn file from a machine that doesn't have a trade lock?

**Comment by scholtzm** [comment]
You could try recycling the SSFN, I personally have not tested it.

**Comment by Netifriik** [comment]
Could you point me to a tutorial/example? I tried generating the sentry file after logging in normally - trade lock. I removed the sentry file and generated a new one through the ssfn file - trade lock or some other error. I'm quite confused by the sentry and ssfn deal.

I'm sorry that I'm such a pain in the arse with this. I'm very grateful that you're willing to help me even if I have little to no idea what I'm doing most of the time.

**Comment by scholtzm** [comment]
All you need to do is take the Steam client's SSFN file and [read it like this](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/examples/offerbot.js#L19). File name's are not important, obviously.
