### ISSUE TITLE
web authentication error 403 only when trying to send trade offers

### ISSUE THREAD

**Issue by Dwynr** [steam-forward/node-steam-forum#86]
edit: worked around web error 403, look at my last post

**Comment by scholtzm** [comment]
Why don't you ask the author what the issue is? :grinning:

**Comment by Dwynr** [comment]
i'm asking why it's always saying web authentication 403 only when sending tradeoffers..
or am i  wrong in here for asking question about node-steam-tradeoffers?..

**Comment by scholtzm** [comment]
Because it fails to send the offer and then it calls webLogOn again.

**Comment by Dwynr** [comment]
okay got the error now, one more question:

how can i get item id's when i receive them -> for sending them to another person in case there are duplicate items

**Comment by Dwynr** [comment]
because assetid's change when i accept a trade.. is there any other way?
