### ISSUE TITLE
Again forEach error.

### ISSUE THREAD

**Issue by jensej** [steam-forward/node-steam-forum#87]
My config:
<pre>
offers.getOffers({
    get_received_offers: 1,
    active_only: 1,
    time_historical_cutoff: Math.round(Date.now() / 1000),
    get_descriptions: 1,
    language: "en_us"
  }, function(error, body) {
    if (error) {
      log(error);
    }
</pre>
Error:
<pre>body.response.descriptions.forEach(function (desc) {
                                ^
TypeError: Cannot read property 'forEach' of undefined
</pre>

**Comment by cymruu** [comment]
variable body.response.descriptions is undefined

**Comment by jensej** [comment]
You mean this:
<pre>
 var descriptions = {};
      body.response.descriptions.forEach(function (desc) {
        descriptions[
          desc.appid + ';' + desc.classid + ';' + desc.instanceid
        ] = desc;
        console.log(desc);
      });

      body.response.trade_offers_received.forEach(function (offer) {
        if (offer.trade_offer_state !== 2) {
          return;
        }

</pre>

**Comment by jensej** [comment]
any ideas?

**Comment by cymruu** [comment]
I told you that body.response.descriptions, try console.log(body), you'll propably get a clue what's wrong

**Comment by jensej** [comment]
but its random, not always.
