### ISSUE TITLE
Unhandled 'error' event - Error: Disconnected.

### ISSUE THREAD

**Issue by metheyes** [steam-forward/node-steam-forum#88]
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/157

To be continued here.. :-)

**Comment by metheyes** [comment]
Okay, my bad. I'm used to it telling me that error was Logon thingy. Anyways! I have an sentry file in the directory where the bot is being run from, why doesn't it use it? I rather not get a trade ban. :7

**Comment by metheyes** [comment]
Solved that as well, I removed getSHA1(). How come that makes it not able to use the sentry?

**Comment by andrewda** [comment]
In the most recent update, the sentry files aren't stored in the same way. Removing `getSHA1()` is the easiest way to convert back to the "old" way of storing the sentry file.

**Comment by metheyes** [comment]
Thanks.
