### ISSUE TITLE
getItems - No session.

### ISSUE THREAD

**Issue by metheyes** [steam-forward/node-steam-forum#89]
```javascript
if(offer.items_to_receive) {
     m_acceptOffer(offer.tradeofferid);
}

function m_acceptOffer(offerid) {
	offers.acceptOffer({tradeOfferId: offerid}, function(error, result) {
		if(error) {
			return console.log(error);
		} else {
			offers.getItems({tradeId: offerid}, function(err, data) {
				if(err) {
					return console.log(err);
				} else {
					return console.log(data);
				}
			});
			return console.log("Accepted a trade-offer! (Offer: " + offerid + ")");
		}
	});
}
```

Error: 
![ss 2015-09-20 at 09 48 27](https://cloud.githubusercontent.com/assets/14365634/9982578/134d5d36-5fd9-11e5-8d2e-4ea6e45c9495.png)

I did read that tradeid & offerid isn't the same, but how do I get the tradeid then? I tried offer.tradeid. :-1:

**Comment by scholtzm** [comment]
[The error is returned anytime it fails to match the regex](https://github.com/Alex7Kom/node-steam-tradeoffers/blob/master/index.js#L305-L309), e.g. steamcommunity.com returns malformed response, not only if the session is dead. The error message should be perhaps generic. cc @Alex7Kom 

Steam is being very slow and unresponsive today, so that might have been the reason.

**Comment by metheyes** [comment]
```javascript
function m_acceptOffer(offerid) {
	offers.acceptOffer({tradeOfferId: offerid}, function(error, result) {
		if(error) {
			return console.log(error);
		} else {
			offers.getItems({tradeId: result}, function(err, data) {
				if(err) {
					return console.log(err);
				} else {
					return console.log(data);
				}
			});
			return console.log("Accepted a trade-offer! (Offer: " + offerid + ")");
		}
	});
}
```

Is my new function, still getting the same problem however.
The trade is being accepted.

**Comment by metheyes** [comment]
Accidently clicked comment and close, lol.

**Comment by metheyes** [comment]
https://github.com/Alex7Kom/node-steam-tradeoffers/issues/123

Seems like I'm not the only one with this problem,

**Comment by scholtzm** [comment]
> result will contain tradeid property

You probably misread my comment.

**Comment by Alex7Kom** [comment]
@scholtzm Thanks for pointing this out! I'll look into it. I don't check params in the library though, this is a job of Steam.

@metheyes As @scholtzm said, you pass the wrong param to `.getItems()`, try to log your `result` var and see.

**Comment by metheyes** [comment]
Thanks! :+1:
