### ISSUE TITLE
SteamID or ApiKey?

### ISSUE THREAD

**Issue by rbJARB** [steam-forward/node-steam-forum#90]
So, I have just tried to run this: https://gist.github.com/Alex7Kom/d764ef2925060c4e7c27
It says put your SteamID on line 10 so I have. When I try to run it, it'll say my ID is illegal. I have filled in the credentials. Should I put my Admin APIKEY in here instead? 
![screen shot 2015-09-21 at 4 52 02 pm](https://cloud.githubusercontent.com/assets/14541442/9988214/2bca8e44-6081-11e5-9be1-ffc8b5f58964.png)

Another question, do I need to edit the first 7 lines? What would I put in them if so? 

Thanks for all the support. rb

EDIT: Just tried doing it exactly the same but using my ApiKey but got the exact same error.

**Comment by Alex7Kom** [comment]
You should put here your 64-bit SteamID. And it says it is illegal because you used wrong quotes.
I've edited the bot so it should be clearer now what to edit: https://gist.github.com/Alex7Kom/d764ef2925060c4e7c27

**Comment by rbJARB** [comment]
Thanks for your help and really quick responce. Unfortunately we still have the same error, my friend has tried it on his Mac but it still has the same error. I have changed the quotes and changed the SteamID to 64 bit. Still no luck

**Comment by Alex7Kom** [comment]
Now you have replaced both quotes with the wrong ones.

**Comment by rbJARB** [comment]
Wow, that was a stupid mistake on my behalf. I'm really sorry for wasting your time.

**Comment by jmarJARB** [comment]
Ok thanks we have fixed all our errors and made it work. Cheers Alex7
