### ISSUE TITLE
Games played error.

### ISSUE THREAD

**Issue by metheyes** [steam-forward/node-steam-forum#92]
When I used: 
```javascript
steamUser.gamesPlayed([730]);
```
within the 'logOnResponse', I get the following error:
![abc](https://cloud.githubusercontent.com/assets/14365634/10094559/04a3fdf2-6359-11e5-82fc-163535493348.png)

**Comment by scholtzm** [comment]
Perhaps you should read the docs.

```js
steamUser.gamesPlayed({
  games_played: [{ game_id: '730' }]
});
```

**Comment by metheyes** [comment]
@scholtzm Used to the "old" node-steam, sorry. Couldn't find it, thanks.
