### ISSUE TITLE
error code 24

### ISSUE THREAD

**Issue by kridan250** [steam-forward/node-steam-forum#95]
Hello, i first logged in to my steambot 7 Days ago and it game me error 24 ofcourse, now 7 Days and a couple of hours later i tried, still the same error... might someone know what is going on here?

the error eppears on exactly this line " if (itemIds[i] == items[j].id){"
in this part of the code:

	var checkItems = [];
																var len = items.length;
																for(var i = 0; i < itemIds.length; i++) {
																	for(var j = 0; j < items.length; j++) {
																		if (itemIds[i] == items[j].id){
																			//console.log('Pushed: ' + items[j].name);
																			var colorObj = helper.getColor(items[j]);
																			
																			checkItems.push({
																				user: data.response.players[0].personaname,
																				ava: data.response.players[0].avatarfull,
																				itemname: items[j].market_name,
																				image: items[j].icon_url,
																				color: colorObj.color,
																				background_color: colorObj.background_color,
																				market_hash_name: items[j].market_hash_name,
																				steamid: offer.steamid_other,
										tradeofferid : offer.tradeofferid

**Comment by andrewda** [comment]
http://forums.backpack.tf/index.php?/topic/20139-steam-trade-offers-errors-what-do-they-mean/

InsufficientPrivileges could mean your cookies aren't up to date or that you have't actually waited the 7 days.
