### ISSUE TITLE
Error sending trade offer (26)

### ISSUE THREAD

**Issue by whocodes** [steam-forward/node-steam-forum#97]
![SSH Output](http://i.imgur.com/TxqlvB1.png)

It logs the options object it passes to makeOffer before executing the function.

All of the items data in the itemsFromMe array are based off of backed up data from trades previously sent to the script.

I can't find any reason for this to be happening based off of what I have.

**Comment by scholtzm** [comment]
Make sure the `assetid`'s are valid.

**Comment by whocodes** [comment]
Why would they not be if they're from trades that were sent to me moments before? How can you verify?

**Comment by scholtzm** [comment]
> from trades that were sent to me moments before

`assetid`s change after each trade (among other things) so that's not gonna work.

**Comment by whocodes** [comment]
So would my best bet be to use loadMyInventory, find the matching market hash and then update the rest?

**Comment by scholtzm** [comment]
Depends on your use case but you could do that.
