### ISSUE TITLE
Cant send steam trade offer .Getting error code 55

### ISSUE THREAD

**Issue by DavidBarishev** [steam-forward/node-steam-forum#98]
Hello<br>
I wanted to be able to send trade offers using the library but i cant get it to work.

This is my code , should be standard.

    var fs = require('fs');
    var crypto = require('crypto');
    
    var Steam = require('steam');
    var SteamWebLogOn = require('steam-weblogon');
    var getSteamAPIKey = require('steam-web-api-key');
    var SteamTradeOffers = require('steam-tradeoffers')
    
    var logOnOptions = {
        account_name: '',
        password: ''
    };
    
    var authCode = ''; // code received by email 
    var sentryFileName = 'sentry'; // steam guard data file name
    
    try {
       logOnOptions.sha_sentryfile = getSHA1(fs.readFileSync(sentryFileName));
    } catch (e) {
        if (authCode !== '') {
            logOnOptions.auth_code = authCode;
        }
    }
    
    if (fs.existsSync('servers')) {
        Steam.servers = JSON.parse(fs.readFileSync('servers'));
    }
    
    var steamClient = new Steam.SteamClient();
    var steamUser = new Steam.SteamUser(steamClient);
    var steamFriends = new Steam.SteamFriends(steamClient);
    var steamWebLogOn = new SteamWebLogOn(steamClient, steamUser);
    var offers = new SteamTradeOffers();
    
    steamClient.connect();
    steamClient.on('connected', function () {
        steamUser.logOn(logOnOptions);
    });
    
    steamClient.on('logOnResponse', function (logonResp) {
        if (logonResp.eresult === Steam.EResult.OK) {
            console.log('Logged in!');
            steamFriends.setPersonaState(Steam.EPersonaState.Online);
            
            steamWebLogOn.webLogOn(function (sessionID, newCookie) {
                getSteamAPIKey({
                    sessionID: sessionID,
                    webCookie: newCookie
                }, function (err, APIKey) {
                    offers.setup({
                        sessionID: sessionID,
                        webCookie: newCookie,
                        APIKey: APIKey
                    }, function () {
                        offer();
                    });
                });
            });
        }
    });
    
    steamClient.on('servers', function (servers) {
        fs.writeFile('servers', JSON.stringify(servers));
    });
    
    steamUser.on('updateMachineAuth', function (sentry, callback) {
        fs.writeFileSync('sentry', sentry.bytes);
        callback({ sha_file: getSHA1(sentry.bytes) });
    });
    
    function getSHA1(bytes) {
        var shasum = crypto.createHash('sha1');
        shasum.end(bytes);
        return shasum.read();
    }
    
    function offer(){
        offers.loadMyInventory({
            appId: 730,
            contextId: 2
        }, function (err, items) {
            var item;
            // picking first tradable item
            for (var i = 0; i < items.length; i++) {
                if (items[i].tradable) {
                    item = items[i];
                    break;
                }
            }
            // if there is such an item, making an offer with it
            if (item) {
                offers.makeOffer({
                    partnerSteamId: "76561198092618890",
                    itemsFromMe: [
                        {
                            appid: 753,
                            contextid: 2,
                            amount: 1,
                            assetid: item.id
                        }
                    ],
                    itemsFromThem: [],
                    message: 'This is test'
                }, function (err, response) {
                    if (err) {
                        throw err;
                    }
                    console.log(response);
                });
            }
        });            
    }

The program logs on ok , but when it tries to send the trade offer , its throwing error : 

    Error: There was an error sending your trade offer.  Please try again later. (55)

I have waited a week after creating my sentry file , so it cant be  it(created on the 25th) I have also tried to use my steam ssfn files but i get the same error.
what am im doing wrong?

**Comment by andrewda** [comment]
Never seen error 55 before, but it means `RemoteCallFailed`. Try hard-coding in all values, and send the offer. Don't know if you meant to do this or not, but `loadMyInventory` is loading appId 730, whereas itemsFromMe contains an item with appId 753. If you're sending a CS:GO item, change that to 730.

**Comment by DavidBarishev** [comment]
OMG, when i first tried the library i found this , but now ..... i feel so stupid! Thanks for the help though the second one fixed it for me!
