### ISSUE TITLE
Error 26.

### ISSUE THREAD

**Issue by metheyes** [steam-forward/node-steam-forum#99]
I've checked & the asset ID's I'm using are matching the ones in the bots inventory.
I can send trades when I use loadmyinventory and send all the items in the users inventory & accept trades.

![ss 2015-10-04 at 01 07 27](https://cloud.githubusercontent.com/assets/14365634/10265536/0652b664-6a2c-11e5-80bb-ff5eb3d9aef4.png)

My item/makeOffer code:

```javascript
				var giveItems= [];
				for(var i = 0; i < rows.length; i++) {
					giveItems.push({'appid': 753, 'contextid': 6, 'amount': 1, 'assetid': rows[i].asset_id }); // <- rows thingy is taken from the database
				}

				offers.makeOffer({
					partnerSteamId: steamid, // already defined
					accessToken: token, // already defined
					itemsFromMe: giveItems,
					itemsFromThem: [],
					message: 'blabla',
				}, function(err, response) {
					if(err) {
						return console.log(err);
					}
});
```
It worked during some time, then it just stopped working. (can't remember if I changed anything in the code, lel)

**Comment by andrewda** [comment]
Are you trying to send CS:GO items? If so, then 753 is no the correct appid.

**Comment by metheyes** [comment]
@andrewda, no. I'm trying to send Steam trading cards.

**Comment by andrewda** [comment]
Are you sure the items are tradable?

**Comment by metheyes** [comment]
@andrewda  Yes. I've added a .withdraw command to automatically add all my items to a trade and send them to me (including the ones I'm trying to trade with the code up there ^. Using my .withdraw command works fine.

**Comment by andrewda** [comment]
And `assetid` is a string, right?

**Comment by metheyes** [comment]
@andrewda Forgot to turn it into a string, sorry & thanks.
